### ISSUE TITLE
請求新增支援Transmission

### ISSUE THREAD

**Issue by xiNeRoar** [LuckyPuppy514/jproxy#10]
希望可以支持Transmission 非常感謝

**Comment by LuckyPuppy514** [comment]
感謝支持，但是由於以下原因，短時間内應該不會添加 Transmission 支持
- 個人未使用過 Transmission ，對 Transmission 不熟悉
- 個人當前對 qBittorrent 還是比較滿意，暫時不會切換至 Transmission

網上大部分人都是建議 qBittorrent 用於下載，Transmission 用於保種，
一般來説， qBittorrent 下載速度更快，但是也更占用資源，Transmission 占用資源較低，適合長時間保種
所以建議安裝一個 qBittorrent 專門用於下載，有問題也歡迎交流

**Comment by xiNeRoar** [comment]
可以請問你是怎麼設定用qb下載之後保種嗎？因為在prowlarr裡設定了很多pt站 試過用qb下載除了很不穩定之外還無法做種...所以才使用更穩定的transmission

**Comment by LuckyPuppy514** [comment]
我比較少玩PT，我一般是只用 qb 下載，做種幾天而已，我這裏倒是沒有出現不穩定的情況，可能是我的種子比較少 😂
qb下載tr做種，可以使用：https://github.com/ledccn/IYUUPlus

**Comment by LuckyPuppy514** [comment]
> 謝謝 我唯有先試看看了 因為找了很久能解決sonarr下載動畫的工具只有你跟xarr rss 而只有你這工具才能完全自動化 所以沒有其他選擇了🙈

v3 已支持 Transmission 种子重命名，但是个人还是推荐 qBittorrent，因为 qBittorrent  既支持种子重命名，又支持文件夹和文件重命名，准确率更高
