### ISSUE TITLE
同步标题后才能格式化标题吗？

### ISSUE THREAD

**Issue by chenhui-97** [LuckyPuppy514/jproxy#101]
从radarr添加电影并立即搜索，因为jproxy是3分钟同步一次标题，此时如果没有匹配到标题，也就没有格式化？

不知是否可以实现搜索时先同步标题，不然radarr已经搜索到符合的，之后同步再格式化也没意义了

立即搜索还会格式化不全
![QQ截图20240308195913](https://github.com/LuckyPuppy514/jproxy/assets/97266858/a719a403-df91-4e88-a0a6-941b05beaae7)

范例里是可以的
![QQ截图20240308200058](https://github.com/LuckyPuppy514/jproxy/assets/97266858/7218e45b-db1f-4656-88ac-16cec943d5e4)

**Comment by LuckyPuppy514** [comment]
1. 新增电影，第一次搜索时，如果找不到对应的标题，会自动同步标题，但是仍然会受到 3 分钟同步一次的规则限制；
2. 搜索是有缓存的，可能同步了标题，但是你已经手动搜索过了，会有缓存，导致 Radarr 中结果仍然是没有格式化

同步时间可以自行修改配置，配置方式请参考文档
添加多个电影时，建议清除一次所有缓存，并手动同步一次标题，然后再进行搜索，否则可能出现第一个电影添加后，同步标题触发同步间隔的限制，导致后续添加的电影标题暂时无法同步

**Comment by chenhui-97** [comment]
> 1. 新增电影，第一次搜索时，如果找不到对应的标题，会自动同步标题，但是仍然会受到 3 分钟同步一次的规则限制；
> 2. 搜索是有缓存的，可能同步了标题，但是你已经手动搜索过了，会有缓存，导致 Radarr 中结果仍然是没有格式化
> 
> 同步时间可以自行修改配置，配置方式请参考文档 添加多个电影时，建议清除一次所有缓存，并手动同步一次标题，然后再进行搜索，否则可能出现第一个电影添加后，其他电影需要同步标题时触发同步间隔的限制，导致后续添加的电影标题暂时无法同步

清除所有缓存，添加并立即搜索就会像上面那样格式化不全

**Comment by chenhui-97** [comment]
同步标题后，清除所有缓存再重新搜索是可以的，直接添加并立即搜索就是不全，是不是没来得及同步完标题就被radarr抓取了

**Comment by chenhui-97** [comment]
破案了，同步标题的时候会获取radarr的文件夹名字，我改了radarr设置在末尾加上tmdbid=，所有别名也跟着改了

**Comment by chenhui-97** [comment]
反复重试还是会复现，是jproxy还没同步完标题就被radarr抓取了？

radarr添加但不立即搜索，jproxy同步标题再清除缓存，再搜索就没问题

**Comment by chenhui-97** [comment]
破案了，原来是radarr用了中文文件夹，jproxy同步标题会使用这个名字，导致直接少了一个英文标题，改回默认后正常了
![QQ截图20240325132421](https://github.com/LuckyPuppy514/jproxy/assets/97266858/8912a411-ac8e-4ae6-b822-7d5b37b68fd5)
