### ISSUE TITLE
【功能讨论】针对番剧分卷发售情况的解析

### ISSUE THREAD

**Issue by Left024** [LuckyPuppy514/jproxy#102]
**问题描述**

如题，现在很多番剧的蓝光碟是分卷发售的，以咒术回战第二季为例

![image](https://github.com/LuckyPuppy514/jproxy/assets/20574903/14a9ad49-370c-4bdb-bd82-d907f0dae91c)

可以看到从标题信息并不能准确解析出每一卷是哪几集，现在的 jproxy 就没办法正确识别并替换名称

但是在内容详情里面是有具体种子文件夹情况的

![image](https://github.com/LuckyPuppy514/jproxy/assets/20574903/c31e3636-bbbb-4963-989f-5e0df68fe79b)

**功能描述**

由上就想到，在解析到标题包含 ```Vol``` 和 ```BD``` 字样的时候，额外从详情里面获取具体是哪几集再重命名

**其它**

其实等蓝光全部发售完肯定会有合集版本使 jproxy 可以解析，不过感觉时间上就太晚了，比如上面举例的咒术回战就有额外的新增画面，不能第一时间自动下载观看，就会感觉有些难受（

**Comment by LuckyPuppy514** [comment]
这种暂时没办法，现在的解析依赖于 Jackett 和 Prowlarr 接口返回的信息，一般是不包含文件列表的
如果要获取文件列表，只能把种子下载下来解析，理论可以实现，但是不太可能查询的时候把每个种子都下载下来判断 😢

**Comment by Left024** [comment]
> 这种暂时没办法，现在的解析依赖于 Jackett 和 Prowlarr 接口返回的信息，一般是不包含文件列表的 如果要获取文件列表，只能把种子下载下来解析，理论可以实现，但是不太可能查询的时候把每个种子都下载下来判断 😢

直接从站点解析可行吗？比如 Jackett 返回的是 nyaa 站点，就从 nyaa 的详情页面去获取（番剧一般也是 nyaa 首发吧，可以限定站点启用此功能）

**Comment by LuckyPuppy514** [comment]
> > 这种暂时没办法，现在的解析依赖于 Jackett 和 Prowlarr 接口返回的信息，一般是不包含文件列表的 如果要获取文件列表，只能把种子下载下来解析，理论可以实现，但是不太可能查询的时候把每个种子都下载下来判断 😢
> 
> 直接从站点解析可行吗？比如 Jackett 返回的是 nyaa 站点，就从 nyaa 的详情页面去获取（番剧一般也是 nyaa 首发吧，可以限定站点启用此功能）

也不可行，每次查询可能有几百上千个结果，不可能每个结果都去网页爬虫，而且每个站点的网页也不一样

**Comment by Left024** [comment]
明白了，谢谢回复
