### ISSUE TITLE
更新jproxy把净标题正则表达式给刷新没了

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#108]
**部署环境（windows / docker）**

docker

**问题描述**

如题，为什么会把之前我自己配置的净标题正则表达式给刷新没了，换成了默认的

**Comment by LuckyPuppy514** [comment]
😅 原来的有BUG，这次升级就覆盖了

**Comment by PN62323424** [comment]
> 😅 原来的有BUG，这次升级就覆盖了

额，我都没备份，下次升级还会冲掉吗。。。

**Comment by LuckyPuppy514** [comment]
下次我做个判断吧
