### ISSUE TITLE
Sonarr Indexer設置問題

### ISSUE THREAD

**Issue by xiNeRoar** [LuckyPuppy514/jproxy#11]
**描述错误情况 - Describe the bug**
在Sonarr裡的indexer明明已經設置好JProxy的IP跟連結，但過幾個小時之後他會自動變回prowlarr的連結

**截图 - Screenshots**
![image](https://user-images.githubusercontent.com/66216186/198824642-723fa87a-7e51-400f-a97e-034ef8e317f9.png)

**请提供以下信息 - Desktop (please complete the following information):**
 - OS: docker
 - Version 2.6.4

**日志 - log**

**Comment by LuckyPuppy514** [comment]
請在：Prowlarr - 應用程序 - 同步級別，選擇：僅添加和刪除 或 禁用，然後保存即可
![image](https://user-images.githubusercontent.com/53246532/198824741-c030cbcc-0c34-48a0-ae84-a7637f312b34.png)

**Comment by xiNeRoar** [comment]
感謝回應得這麼快速！
