### ISSUE TITLE
支援搜尋國產電視劇及Radarr搜尋電影

### ISSUE THREAD

**Issue by xiNeRoar** [LuckyPuppy514/jproxy#12]
**描述你的需求 - Describe Requirement**
希望可以Sonarr支援國產電視劇及Radarr搜尋動畫電影

**Comment by LuckyPuppy514** [comment]
1. 國產電視劇需要 PT，BT 很少，然後添加發佈組規則即可（按WIKI自己寫或者提供幾個較規範例子，我可以幫忙寫）
2. Radarr 搜索動漫電影搜不到一般就是得用中文標題搜索，一部寫一個規則比較麻煩，用了就沒用了，後續可能會考慮添加 TMDB 來獲取中文標題搜索（待定，得有時間 🤣）

**Comment by zhuzhe1983** [comment]
希望支持Lidarr, Lidarr现在用musicbrainz返回的都是繁体中文，然后去pt/bt站下载都抓不到。想改成简体中文去搜索。

**Comment by LuckyPuppy514** [comment]
> 希望支持Lidarr, Lidarr现在用musicbrainz返回的都是繁体中文，然后去pt/bt站下载都抓不到。想改成简体中文去搜索。

1. 个人没有使用 Lidarr
2. Lidarr 应该是直接连接 musicbrainz，没有通过 jackett / prowlarr 吧，我这个主要是在 sonarr 和 jackett / prowlarr 之间过滤格式化相关数据
所以，应该暂时不会添加相应支持，不过如果只是繁体转简体就可以的话，应该不难，后续如果有折腾+时间，我会看看 😂

**Comment by LuckyPuppy514** [comment]
> **描述你的需求 - Describe Requirement** 希望可以Sonarr支援國產電視劇及Radarr搜尋動畫電影

v3.0.0 已支援

**Comment by zhuzhe1983** [comment]
> 
prowlarr是支持lidarr的哈，可以在prowlarr主动添加

![image](https://user-images.githubusercontent.com/1917345/232990826-70a90b96-3bca-476a-8988-f11a4e48cdb0.png)

**Comment by LuckyPuppy514** [comment]
> > 
> 
> prowlarr是支持lidarr的哈，可以在prowlarr主动添加
> 
> ![image](https://user-images.githubusercontent.com/1917345/232990826-70a90b96-3bca-476a-8988-f11a4e48cdb0.png)

暂时还是没有添加 lidarr 的计划，个人没有使用，身边用的人也不多 😂
