### ISSUE TITLE
如果有中日双语字幕的，优先下载双语字幕的种子。没有中日双语的优先下载中文种子，当中日双语字幕出来后，自动替换为中日双语字幕的

### ISSUE THREAD

**Issue by appotry** [LuckyPuppy514/jproxy#13]
# 分类 - Type
1. 发布组 - ReleaseGroup
2. 动漫 - Anime
3. 电视剧 - TV Serial
4. 综艺 - TV Show
5. 其他 - Others

请输入你的选择 - 2

# 请提供三个以上标题例子 - please provide 3 or more example title
...

如果有中日双语字幕的，优先下载双语字幕的种子。没有中日双语的优先下载中文种子，当中日双语字幕出来后，自动把单独中文字幕的视频替换为中日双语字幕的。这个需求有实现方案没？

如下例子 https://mikanani.me/ 想下载喵萌奶茶屋的简日双语字幕版本

[【喵萌奶茶屋】★10月新番★[异世界舅舅/Isekai Ojisan][08][1080p][繁日双语][招募翻译] [576MB]](https://mikanani.me/Home/Episode/d8a25a939b955158eeb63575f81f4f6dca8bfa29) [复制磁连]2022/11/27
[【喵萌奶茶屋】★10月新番★[异世界舅舅/Isekai Ojisan][08][720p][繁日双语][招募翻译] [287.9MB]](https://mikanani.me/Home/Episode/d41c895dbaa230cfabffdd6107350116e3face7a) [复制磁连]2022/11/27
[【喵萌奶茶屋】★10月新番★[异世界舅舅/Isekai Ojisan][08][1080p][简日双语][招募翻译] [576.3MB]](https://mikanani.me/Home/Episode/be07ab9d4a382090992dfd8d7e1fadf2032bb70e) [复制磁连]2022/11/26
[【喵萌奶茶屋】★10月新番★[异世界舅舅/Isekai Ojisan][08][720p][简日双语][招募翻译] [288MB]](https://mikanani.me/Home/Episode/b8c43e4393a5b16782e9d79dcea3ed0f3235c132) [复制磁连]2022/11/26
[【喵萌奶茶屋】★07月新番★[异世界舅舅/Isekai Ojisan][07][1080p][繁日双语][招募翻译] [498.2 MB]](https://mikanani.me/Home/Episode/f05da1935b0a62ac56632e64df297ee9cd280af7) [复制磁连]2022/09/02
[【喵萌奶茶屋】★07月新番★[异世界舅舅/Isekai Ojisan][07][720p][繁日双语][招募翻译] [240.19 MB]](https://mikanani.me/Home/Episode/05b1568a179bad14f18453fac5a9a1e07591667d) [复制磁连]

sonarr 的手动搜索，有个Filter按钮，手动点击Filter可以定制搜索规则。这个规则不知道对自动搜索有没有效

sonarr似乎没有语言版本升级更新功能？ 但是有分辨率，码率质量更新替换规则。把中日双语字幕的设置为更高分分辨率或者码率可以解决标题问题，但是解决方案不是很好，有更好的方案没

**Comment by appotry** [comment]
sonarr 种子的 Language 标签显示中文过滤中文剧集名称可以得到。是添加zh 还是怎么添加了？

**Comment by appotry** [comment]
sonarr meta 元数据还不支持中文，去sonarr提问了，说是sonarr v3版本才会添加多语言支持。radarr早就支持多语言了

**Comment by LuckyPuppy514** [comment]
你这个需求直接通过 sonarr 就可以实现了
Custom Formats，自定义关键字，匹配出来中日双语
Profiles，自定义分数，分数高的会优先下载
- v3 好像没有升级选项，但是也会自动升级？
- v4 测试版本已经和 radarr 差不多了，我的是 v4 测试版：[https://hub.docker.com/r/linuxserver/sonarr/tags](https://hub.docker.com/r/linuxserver/sonarr/tags)）

> 不是项目直接相关问题，建议加Q群：921905633 讨论 😂

![image](https://user-images.githubusercontent.com/53246532/205289604-bfb37eb6-ccaf-469f-9ba9-340fc6435909.png)

**Comment by appotry** [comment]
这个Custom Formats 的规则怎么写？ @LuckyPuppy514

**Comment by LuckyPuppy514** [comment]
根据标题用正则匹配就行了，比如：.*简日双语.*
![image](https://user-images.githubusercontent.com/53246532/205401077-18aa12c1-5b1f-41ab-9b62-6866d58435f9.png)
