### ISSUE TITLE
qBittorrent认证支持

### ISSUE THREAD

**Issue by mepwang** [LuckyPuppy514/jproxy#14]
我的qBittorrent的web interface带有认证，在JProxy的qBittorrent代理配置页面中
没有找到填写用户名和密码的地方，请问这是不支持qBittorrent的认证模式吗

**Comment by LuckyPuppy514** [comment]
支持的，只需在 sonarr 配置好账户密码即可

> sonarr 请求qBittorrent时会携带认证信息，并传递给 jproxy，所以无需在 jproxy 配置认证信息

```mermaid
graph LR
    1[Sonarr] == 请求qBittorrent ==> 2(JProxy) == 转发sonarr请求 ==> 3(qBittorrent) 
    3(qBittorrent)  == 返回结果 ==> 2(JProxy) == 返回结果 ==> 1[Sonarr]
```
