### ISSUE TITLE
申请支持transmission

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#15]
我身边朋友不少都是用transmission的，感觉上传快一点，请问有没有计划支持这个下载器

**Comment by LuckyPuppy514** [comment]
我有空研究下，不过得等年后了，～(￣▽￣～)~

**Comment by LuckyPuppy514** [comment]
v3.0.0 预留了 transmission 的接口，但是由于 
- transmission 并不能像 qBittorrent 那样直接修改传回给 Sonarr 的数据（修改了会导致 Sonarr 找不到文件，而 qBittorrent 则不会，推测 Sonarr 是利用种子 HASH 对应 qBittorrent 的文件的）
- transmission 只有 RPC ，没有 API，而且几个开源的 java RPC 早已经年久失修，只能等待大佬写一个 java 版修改种子名称的 RPC 工具 QAQ

**Comment by LuckyPuppy514** [comment]
![20230414115623](https://user-images.githubusercontent.com/53246532/231938155-64803892-237d-41fb-8f8c-9b6d06721659.gif)

v3.1.3 已支持 Transmission 种子重命名功能
