### ISSUE TITLE
qBittorrent  HTTPS

### ISSUE THREAD

**Issue by dysf888** [LuckyPuppy514/jproxy#16]
[https://github.com/LuckyPuppy514/jproxy/issues/14](https://github.com/LuckyPuppy514/jproxy/issues/14)
如果 qbit 部署在 其他地方且 开启了 反向代理 则无法使用

**Comment by LuckyPuppy514** [comment]
1. 同一个内网，建议直接使用内网IP；
2. 非同一个内网，反向代理一般也不会影响，有问题请描述清楚自己的环境，以及复现问题的操作流程，最好附上相关配置，截图等信息

**Comment by dysf888** [comment]
qbit 通过 cloudflare zero trust 反向代理后 是 tls 的 ，如果放弃zero trust 非同一个内网是没有问题的

**Comment by LuckyPuppy514** [comment]
1. cloudflare zero trust 我不太清楚，我反代一般都是用 nginx，一般来说，还是建议部署到同一个内网，方便安全
2. 如果不能同一个内网，就只能暂时先采用你的方案，或者直接使用 ip+开放端口的方式了（怕不安全可以考虑防火墙限制白名单 ip 访问对应端口）
3. 后续如果有空的话，我会测试下反代和https，不过现在暂时不影响使用，所以可能会放在后面考虑（现在在考虑的是重构和优化，并利用 TMDB 接口获取中文标题，应该可以减少很多规则，还能提升识别率，不过不知道啥时候有空 🤣）

**Comment by dysf888** [comment]
okk

> 1. cloudflare zero trust 我不太清楚，我反代一般都是用 nginx，一般来说，还是建议部署到同一个内网，方便安全
> 2. 如果不能同一个内网，就只能暂时先采用你的方案，或者直接使用 ip+开放端口的方式了（怕不安全可以考虑防火墙限制白名单 ip 访问对应端口）
> 3. 后续如果有空的话，我会测试下反代和https，不过现在暂时不影响使用，所以可能会放在后面考虑（现在在考虑的是重构和优化，并利用 TMDB 接口获取中文标题，应该可以减少很多规则，还能提升识别率，不过不知道啥时候有空 🤣）
