### ISSUE TITLE
ANI规则正则多了个"简中",导致拉取的名称都被认为是简体

### ISSUE THREAD

**Issue by Cattleyan** [LuckyPuppy514/jproxy#17]
**描述错误情况 - Describe the bug**
请尽可能清楚的描述你遇到的问题

**截图 - Screenshots**
请提供错误全屏截图

**请提供以下信息 - Desktop (please complete the following information):**
 - OS: [e.g. docker/linux/windows]
 - Version [e.g. 2.5.1]

**日志 - log**
请提供详细的错误日志
Please provide web_error.log.

**Comment by LuckyPuppy514** [comment]
当初考虑到存在这种情况，所有一律都追加了 `[简中]` 
```text
[ANi] Skeleton Knight in Another World - 骸骨騎士大人異世界冒險中[01][1080P][Baha][WEB-DL][AAC AVC][MP4]
```
如果有个别错误，可以考虑在 sonarr 中添加拒绝规则

![image](https://user-images.githubusercontent.com/53246532/224742188-67bf4be3-6563-45f9-aa14-4d66e995576b.png)

或者关闭这条规则，自行新增一条，把追加的 `简中` 去掉

最后，最近在大版本重构中，新版本匹配规则会有所变动，也可以等新版本，不过估计还得一两个月 🤣

**Comment by Cattleyan** [comment]
> 

与[ANi][间谍家家酒] SPY×FAMILY 13 [1080P][Baha][WEB-DL][AAC AVC]**[CHT]**[MP4]繁简体冲突
个别视频存在繁简双字来着也不方便添加到拒绝规则
主要还是每次重启都要从服务器下载配置文件,还得手动删除挺麻烦的

**Comment by LuckyPuppy514** [comment]
你可以暂时先关闭这条规则，新增一条一样的，把 `简中` 去掉即可，这样就不会被同步的覆盖掉

**Comment by LuckyPuppy514** [comment]
> **描述错误情况 - Describe the bug** 请尽可能清楚的描述你遇到的问题 A clear and concise description of what the bug is.
> 
> **截图 - Screenshots** 请提供错误全屏截图 If applicable, add screenshots to help explain your problem.
> 
> **请提供以下信息 - Desktop (please complete the following information):**
> 
> * OS: [e.g. docker/linux/windows]
> * Version [e.g. 2.5.1]
> 
> **日志 - log** 请提供详细的错误日志 Please provide web_error.log.

v3.0.0 已经发布，已修复该问题
