### ISSUE TITLE
v3.0.0 已经发布，规则问题请统一在此反馈

### ISSUE THREAD

**Issue by LuckyPuppy514** [LuckyPuppy514/jproxy#18]
请参考下列反馈格式

类型：规则识别错误 / 规则新需求

```
[SweetSub][銃動彼岸花][Lycoris Recoil][07][WebRip][1080P][AVC 8bit][繁體內嵌]
[SweetSub][铳动彼岸花][Lycoris Recoil][07][WebRip][1080P][HEVC 10bit][简繁内封]
[SweetSub][铳动彼岸花][Lycoris Recoil][07][WebRip][1080P][AVC 8bit][简体内嵌]
......
```

**Comment by whetherTsmile** [comment]
类型:规则识别错误
[Lilith-Raws] 鬼滅之刃 刀匠村篇 / Kimetsu no Yaiba - Katanakaji no Sato-Hen - 01 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]
识别为
Demon Slayer: Kimetsu no Yaiba S1E1 [繁中][1080P][WEBDL][Lilith-Raws
【豌豆字幕组&风之圣殿字幕组】★04月新番[鬼灭之刃 刀匠村篇 / Kimetsu_no_Yaiba-Katanakaji_no_Sato_Hen][01(45)][简体][1080P][MP4]
识别为
Demon Slayer: Kimetsu no Yaiba S1 [简中][1080P][豌豆字幕组&风之圣殿字幕组]

能不能让他根据sonarr的绝对序号来识别

**Comment by LuckyPuppy514** [comment]
标题排序有点问题，先匹配到了中文标题了，我本地调试好了，晚点或者明天发布版本

![image](https://user-images.githubusercontent.com/53246532/230894458-386d7620-f801-4485-b547-756eaaf74cd8.png)

**Comment by LuckyPuppy514** [comment]
v3.0.9 已发布，规则也有变动，升级后建议手动同步一下规则（定时每天同步一次）

**Comment by PN62323424** [comment]
> v3.0.9 已发布，规则也有变动，升级后建议手动同步一下规则（定时每天同步一次）

我用了一段时间新版，搜索词好像只能改标题名，没法把标题后面的季或者集也改掉。这个功能我感觉还是能用到的。

比如sonarr在选择standed的情况下是无法搜索到xxx 01这样的剧集的，即standed下无法追剧， 但只需要把xxx S01E01这样的搜索词匹配下，比如这样匹配下(.*)\sS\d+E(\d+)，然后S01E01替换成01，standed模式就可以实现自动追剧了。这样就不用standed和anime切换了

**Comment by LuckyPuppy514** [comment]
> > v3.0.9 已发布，规则也有变动，升级后建议手动同步一下规则（定时每天同步一次）
> 
> 我用了一段时间新版，搜索词好像只能改标题名，没法把标题后面的季或者集也改掉，这个功能我感觉很多场景还是能用到的。
> 
> 比如sonarr在选择standed的情况下是无法搜索到xxx 01这样的剧集的，即standed下无法自动追动漫番剧， 但只需要把xxx S01E01这样的搜索词匹配下，比如这样匹配下(.*)\sS\d+E(\d+)，然后S01E01替换成01，standed模式就可以实现自动追剧了。这样就不用standed和anime切换了。
> 
> 如果有需要，我还可以列出好几个应用场景。

请自行删除该问题，另开一个 issue，这里是处理剧集规则和电影规则的地方。。。

**Comment by Archer-Tatsu** [comment]
> [豌豆字幕组&风之圣殿字幕组&LoliHouse] 鬼灭之刃 刀匠村篇 01(45) / Kimetsu no Yaiba - 45 [WebRip 1080p HEVC-10bit AAC][简繁外挂字幕]

识别为
> Demon Slayer: Kimetsu no Yaiba S1E45 [简繁][外挂][1080P][WEBRip][-LoliHouse]

貌似把集编号01当成季编号了。另外就是鬼灭之刃在thexem上anidb的绝对集数和sxxexx的集数是一样的，反而是tvdb上的绝对集数是真·绝对集数……但是目前观察到sonarr好像不会用tvdb的绝对集数去搜索（比如这个case下我看搜索记录没有搜过45，然后它也无法匹配到45这个绝对集数），这个是不是目前无解了……

**Comment by LuckyPuppy514** [comment]
> > [豌豆字幕组&风之圣殿字幕组&LoliHouse] 鬼灭之刃 刀匠村篇 01(45) / Kimetsu no Yaiba - 45 [WebRip 1080p HEVC-10bit AAC][简繁外挂字幕]
> 
> 识别为
> 
> > Demon Slayer: Kimetsu no Yaiba S1E45 [简繁][外挂][1080P][WEBRip][-LoliHouse]
> 
> 貌似把集编号01当成季编号了。另外就是鬼灭之刃在thexem上anidb的绝对集数和sxxexx的集数是一样的，反而是tvdb上的绝对集数是真·绝对集数……但是目前观察到sonarr好像不会用tvdb的绝对集数去搜索（比如这个case下我看搜索记录没有搜过45，然后它也无法匹配到45这个绝对集数），这个是不是目前无解了……

该标题过于混乱（中文是季标题，英文是通用标题，有相对集数，又绝对集数），且是极个别情况，而且存在不少可以正确识别的资源，因此不做修正

**Comment by maodun96** [comment]
类型：规则识别错误
【极影字幕社】小智是女孩子! 第13集 GB_CN HEVC_opus 1080p 
未被识别为简中。

**Comment by LuckyPuppy514** [comment]
> 类型：规则识别错误 【极影字幕社】小智是女孩子! 第13集 GB_CN HEVC_opus 1080p 未被识别为简中。

[已修复](https://github.com/LuckyPuppy514/jproxy/commit/652057a5a9d025afb3ca2bad4d3808042a5caf14)

![image](https://user-images.githubusercontent.com/53246532/235802980-8680b7f4-7cf2-4721-ba8f-783ab16a0eec.png)

**Comment by LuckyPuppy514** [comment]
> 类型：规则识别错误 skip.and.loafer.s01e06.1080p.web.h264-senpai[eztv.re] 识别为 Skip and Loafer S1 [1080P]

已修复，手动同步或等每天定时同步规则即可

**Comment by LuckyPuppy514** [comment]
> Fear the Walking Dead会被识别为Walking Dead，造成如果想下The Walking Dead会下到Fear the Walking Dead，我观察了下，净标题里的the都会被去掉，这样可能会造成一些误识别

因为 Fear the Walking Dead 包含了 The Walking Dead，暂时没办法根治，目前有两种办法修正：

1. 在 Sonarr 订阅 Fear the Walking Dead，在 JProxy 同步剧集标题

2. 手动添加标题规则修正
```bash
.*\b((?i)Fear the Walking Dead)\b.*
```
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/c3ddcf74-e0df-4ddf-99e3-f6e7c5407675)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/844af585-7179-47a9-92f4-ff94b345f7c9)

**Comment by PN62323424** [comment]
很多带the的都被去掉了，the company被改成了company。the pacific被改成了pacific，去掉the是出于什么原因，这样感觉会造成一些误识别吧？

**Comment by LuckyPuppy514** [comment]
> 很多带the的都被去掉了，the company被改成了company。the pacific被改成了pacific，去掉the是出于什么原因，这样感觉会造成一些误识别吧？

有错误再说吧，你这个错误不是由于 the 造成的

**Comment by PN62323424** [comment]
THE iDOLM@STER Cinderella Girls U149这部无法搜出任何结果，我尝试把净标题正则表达式里的@去掉了，但净标题就变成了t h e i d o l m @ s t e r c i n d e r e l l a g i r l s u 1 4 9（我没用TMDB标题因为搜索的太慢了）

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/ca7ee819-df25-4102-8ce1-5cc5390cd889)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/fe55a3b1-1759-4e19-aabb-c1668644ad9f)

1. 我个人测试，原标题也是能查到结果的
2. 如果不行，建议在 TMDB 手动新增标题（不用填写 TMDB 密钥）

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/ddccc8ff-740b-41f9-8b98-499757adb64f)

**Comment by PN62323424** [comment]
我禁用了tmdb，可能是这个原因，主要开了这个的话PT站点我怕容易挂

**Comment by LuckyPuppy514** [comment]
> 我禁用了tmdb，可能是这个原因，主要开了这个的话PT站点我怕容易挂

TMDB 无法禁用，只是不填 APIKEY 不会同步标题（搜索和结果都无法使用 TMDB 标题），所以手动添加标题即可
而且我也有  PT 站点，只要不在短时间内多次点击手动查询，一般就不会有问题，除了馒头频率限制比较高，可能会被暂时屏蔽

**Comment by PN62323424** [comment]
> 

比如12集的动漫，如果手动搜一次，基本这些BT站点都会挂的，即便没开TMDB。如果能控制下搜索频率就好了。

**Comment by LuckyPuppy514** [comment]
> > 
> 
> 比如12集的动漫，如果手动搜一次，基本这些BT站点都会挂的，即便没开TMDB。如果能控制下搜索频率就好了。

动漫搜索整季，第几季搜索第几集就能找到对应季的合集包，不要点整季搜索，Sonarr 整季搜索都是一集一集搜索的，我无法控制

**Comment by PN62323424** [comment]
The Story of Chuaner这部搜不出结果来

```
05-27 17:27:03 Info Torznab search in HDArea for Story of Chuaner S03 => Found 0                                                                                                                                                              releases [577ms]
```

**Comment by LuckyPuppy514** [comment]
> The Story of Chuaner这部搜不出结果来，我试了好几个站大部分结果都出不来，实际站内有的
> 
> ```
> 05-27 17:27:03 Info Torznab search in HDArea for Story of Chuaner S03 => Found 0                                                                                                                                                              releases [577ms]
> ```

```text
05-28 08:39:12 Info Torznab search in Audiences for Story of Chuaner S03 => Found 2 releases [2022ms] 
05-28 08:39:13 Info Torznab search in Audiences for 人生一串 S03 => Found 2 releases [1158ms] 
05-28 08:39:14 Info Torznab search in Audiences for 人生一串 S03 => Found 2 releases [1171ms] 
05-28 08:39:16 Info Torznab search in Audiences for 人生一串 => Found 8 releases [1190ms] 
```

亲测没问题，我没有 HDArea 这个站，我也不知道有没有，而且你给的日志就搜索了英文标题，建议添加 TMDB APIKEY 开启中文标题搜索（非美剧大部分都需要，否则很多可能有问题），或者在 JProxy 手动添加 TMDB 标题

**Comment by PN62323424** [comment]
你可以试着馒头搜这部的第一季，搜不到的，这部基本都是英文标题，没中文标题，而且加了中文标题也搜不到

**Comment by PN62323424** [comment]
馒头上这部第一季的标题是：The Story Of Chuaner 2018 WEB-DL 1080p H264 AAC-HDCTV

jackett日志：
```
05-28 16:40:18 Info Torznab search in M-Team - TP (2FA) for Story of Chuaner S01 => Found 0 releases [7069ms]
```

搜不到第一季的结果，即便加了TMDB的中文也搜不到

**Comment by LuckyPuppy514** [comment]
> 馒头上这部第一季的标题是：The Story Of Chuaner 2018 WEB-DL 1080p H264 AAC-HDCTV
> 
> jackett日志：
> 
> ```
> 05-28 16:40:18 Info Torznab search in M-Team - TP (2FA) for Story of Chuaner S01 => Found 0 releases [7069ms]
> ```
> 
> 搜不到第一季的结果，即便加了TMDB的中文也搜不到
> 
> 泰剧馒头上标题：I Told Sunset About You 2020 Complete WEB-DL 1080p H264 AAC 这部也搜不到。。。

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/aec4a00d-20b6-439b-b9f6-2839634eaf4c)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/74ff7074-7f10-4295-b886-edcac5af1f0f)

1. 你这属于非规则问题，请勿在此 issue 提问了，建议有问题重新开 issue
2. 我早上和现在测试，观众和馒头均能搜到结果
3. 按照你提供的日志，如果只有一个英文标题搜索，那么就是你的 TMDB 标题没有同步，或者有缓存，文档都有明确说明（设置完建议手动同步一次标题，如果没有生效建议清理所有缓存），请认真查阅文档，确保 Prowlarr / Jackett 日志中搜索像我的一样，有中文标题
