### ISSUE TITLE
关于字幕组识别不到的问题

### ISSUE THREAD

**Issue by luvisiki** [LuckyPuppy514/jproxy#2]
![image](https://user-images.githubusercontent.com/65345064/179045581-7b47fe8a-f605-4992-9400-b1dd41104ecf.png)
猎户发布不鸽组 识别不到的问题进行反馈

**Comment by LuckyPuppy514** [comment]
能把整个标题复制发我下吗

**Comment by luvisiki** [comment]
[[猎户不鸽发布组] 即使如此依旧步步紧逼 / 就算这样，“步”还是靠了过来 / Soredemo Ayumu wa Yosetekuru 01 [1080p] [简中内嵌] [2022年7月番]](https://mikanani.me/Home/Episode/5d16e433e16ff0bb8a6c8f74d2be6031ccfd5e68)

**Comment by LuckyPuppy514** [comment]
好了，重启服务，就会自动更新正则了

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/179052259-35410cd6-3b51-4956-90c8-64437cacd399.png)

**Comment by luvisiki** [comment]
非常感谢！！
