### ISSUE TITLE
求问为啥3.0给我的johnwick 全匹配成福音战士了

### ISSUE THREAD

**Issue by origalin** [LuckyPuppy514/jproxy#20]
![image](https://user-images.githubusercontent.com/9404305/230550753-18e1c9ba-bbba-43c5-9df1-ea3439c76ea9.png)
如图，标题原文John Wick Chapter 4 2023 V2 1080p HDTS x264 AAC

**Comment by origalin** [comment]
来源 https://kickasstorrents.to/john-wick-chapter-4-2023-v2-1080p-hdts-x264-aac-t5614333.html

**Comment by LuckyPuppy514** [comment]
1. 请贴全屏截图
2. 请贴上对应两部影片，搜索到的标题，先用标题关键字找，然后用 TMDB ID，把所有标题搜索截图上来

![image](https://user-images.githubusercontent.com/53246532/230566871-91d24e78-b9be-4ba4-be19-927ff0c0755c.png)
![image](https://user-images.githubusercontent.com/53246532/230566948-5f306fc7-a1ff-4a43-93f8-9b87a2310a7f.png)

**Comment by LuckyPuppy514** [comment]
找到问题了，福音这个标题有个特殊字符 | 导致的，更新到最新版，重新同步下电影标题（也可以等定时同步）

![image](https://user-images.githubusercontent.com/53246532/230588400-07498843-46a1-4b7e-a96a-fdf694de905c.png)
![image](https://user-images.githubusercontent.com/53246532/230588543-cd301b5f-7007-4f45-a26b-830c9bf4e6e2.png)

**Comment by origalin** [comment]
非常感谢！
