### ISSUE TITLE
Prowlarr連不通

### ISSUE THREAD

**Issue by xiNeRoar** [LuckyPuppy514/jproxy#21]
![image](https://user-images.githubusercontent.com/66216186/230588000-eeb651ec-a5b6-4081-88db-d4fb72f50122.png)
![image](https://user-images.githubusercontent.com/66216186/230588193-b93f3d9a-f845-4576-9ebe-3cfdf2a0c93d.png)

嘗試過以下組合全部不成功;
http://192.168.1.112:9696/
http://192.168.1.112:9696
192.168.1.112:9696/
192.168.1.112:9696

**Comment by LuckyPuppy514** [comment]
首先，格式上，这两个都没问题
```
http://192.168.1.112:9696/
http://192.168.1.112:9696/
```
你这个问题是 JProxy 所在服务器（注意不是你的浏览器）无法联通你的 Prowlarr 
你得进服务器测试，输入如下命令，应该直接返回空信息

```
curl http://192.168.1.112:9696
```
![image](https://user-images.githubusercontent.com/53246532/230589007-a8ea3d80-337a-4efc-992b-915c5d99b39b.png)
![image](https://user-images.githubusercontent.com/53246532/230589203-3495a49b-6d83-49bb-a14c-5eeed7f711ac.png)

**Comment by xiNeRoar** [comment]
我照你的做法進去portainer之後輸入指令，一按確認之後什麼都沒有跳回輸入指令的畫面，並沒有出現你第二張圖的資訊
![image](https://user-images.githubusercontent.com/66216186/230589923-fab5e3df-4ec3-4b1a-9db0-6076bd2ddc85.png)

**Comment by LuckyPuppy514** [comment]
这里不是给你执行命令的，请保持默认值 /bin/bash
进去后才是执行命令的地方

![image](https://user-images.githubusercontent.com/53246532/230590129-287c94ba-33a4-4188-bee5-69a21208a4e4.png)

**Comment by xiNeRoar** [comment]
謝謝你的解說，以下是我根據你的指令輸入後出現的畫面
![image](https://user-images.githubusercontent.com/66216186/230590503-4de4bbd9-bc0e-4e12-907e-6c310d29bb0f.png)

**Comment by xiNeRoar** [comment]
與此同時我在jproxy的log裡發現了這些error 不知道有沒有關係
![image](https://user-images.githubusercontent.com/66216186/230590640-d81ef540-0895-46fe-913d-0f33a147fa09.png)

**Comment by LuckyPuppy514** [comment]
你是不是每点击保存。。。

![image](https://user-images.githubusercontent.com/53246532/230591619-12b2c5f9-0475-4318-a47a-bc0a56009717.png)

**Comment by xiNeRoar** [comment]
我有點擊保存，看到上圖有401 Unauthorize 之後我猜想問題可能在於我的prowlarr有設定登入帳密，會不會是這位原因導致沒法連通

**Comment by LuckyPuppy514** [comment]
我的也有，没有问题

![image](https://user-images.githubusercontent.com/53246532/230592099-5def374c-baf2-4ebf-88e3-37129b3d1257.png)

日志显示错误，是你输入的 Prowlarr 地址有问题，你输入的是

```text
192.168.1.112:9696
localhost:9696
http://localhost:9696
```

我上面已经说了，这个才是正确的格式

```text
http://192.168.1.112:9696
```

**Comment by LuckyPuppy514** [comment]
如果你输入正确的地址，保存时还是报 401 错误，可尝试进行如下设置

![image](https://user-images.githubusercontent.com/53246532/230592453-1767f1eb-d174-493b-8b90-20ceb8907aa3.png)

**Comment by xiNeRoar** [comment]
謝謝，按你的設置終於成功連通了
