### ISSUE TITLE
能否增加qb改文件名功能？增加文件导入成功率

### ISSUE THREAD

**Issue by maodun96** [LuckyPuppy514/jproxy#25]
因为遇到一个情况，lolihouse的一部番剧下载文件后，文件名不包含“简繁”。被sonarr识别成英文了。

**Comment by LuckyPuppy514** [comment]
这功能已经有了呀。。。只是没有直接修改 qBittorrent 的文件名，而是在下载完成时，传输给 Sonarr 时候修改了
