### ISSUE TITLE
想问下优化搜索关键字的问题

### ISSUE THREAD

**Issue by StoneShiLei** [LuckyPuppy514/jproxy#28]
我sonarr订阅韩剧：重启人生，sonarr默认搜索关键字是rebooting
jproxy可以把rebooting替换为重启人生
但看prowlarr的搜索记录里，实际上搜索关键字是：重启人生 s01e08
而bt站资源的季度集数可能没有写季度，而集数也不带‘e’
比如：
【幻月压制】【23年日剧】【重启人生】【08】【1080P】【官方中字】
重启人生第04集.mp4
这种在bt站上就无法搜索出来
想问下如何修改查询bt站时的季度和集数关键字？

图为comicat搜索‘重启人生‘和'重启人生 S01'的结果
![image](https://user-images.githubusercontent.com/24240891/231750119-54d96893-f473-4877-8014-89bb8680f6ea.png)
![image](https://user-images.githubusercontent.com/24240891/231750154-7d7d3d54-3dfd-4af7-8914-31f5bfe03a37.png)
![image](https://user-images.githubusercontent.com/24240891/231750190-3783823b-c7ad-4295-99d3-efba7c4d58f0.png)

**Comment by StoneShiLei** [comment]
> 是只有这一个，还是日剧都这样？

我找到原因了，之前用了一个叫alternatrr 的项目，改了sonarr的数据库，我把系列删了重建就好了，现在搜索关键字就不再是“重启人生 S01E07”，而是“重启人生 00”了，00可能是因为这个剧在tvdb上有问题还是啥的，如下图，黄色叹号hover上去提示：Episode does not have an absolute episode number
![image](https://user-images.githubusercontent.com/24240891/231787306-a3fe46d4-0b16-4554-8a05-fdb3350a27ab.png)
![image](https://user-images.githubusercontent.com/24240891/231787417-7923c447-1d2c-4723-869e-5b52230101ce.png)

**Comment by StoneShiLei** [comment]
> > 是只有这一个，还是日剧都这样？
> 
> 我看了下，好像都这样，黑暗荣耀、重启人生，这种韩剧日剧都这样，英文搜索是正常的，但中文就有带有S01E01这种的
> 
> 而且中文的在prowlarr的查询字段上显示的是 重启人生，而点到bt站里会发现搜索字段实际上是 重启人生 S01E07

又看了下，所有tv类型的都这样，无论搜索的关键字是中文还是英文，都会带个S01  或者S01E07这种，会导致bt站搜不到

**Comment by Archer-Tatsu** [comment]
应该是sonarr在搜动画的时候会尝试搜索多种关键字（因为动画很多是用absolute number编号的），包括 {series name} sxxexx或者 {series name} {absolute number}这些，可能普通电视剧就不会用absolute number搜索，试试sonarr里标记这个剧是个动画（我记得是在添加剧集的时候可以标记）是不是有用？

**Comment by LuckyPuppy514** [comment]
> 应该是sonarr在搜动画的时候会尝试搜索多种关键字（因为动画很多是用absolute number编号的），包括 {series name} sxxexx或者 {series name} {absolute number}这些，可能普通电视剧就不会用absolute number搜索，试试sonarr里标记这个剧是个动画（我记得是在添加剧集的时候可以标记）是不是有用？

我一开始也是这样想，然而，Sonarr 电视剧根本没有绝对集数，😂

**Comment by Archer-Tatsu** [comment]
> > 应该是sonarr在搜动画的时候会尝试搜索多种关键字（因为动画很多是用absolute number编号的），包括 {series name} sxxexx或者 {series name} {absolute number}这些，可能普通电视剧就不会用absolute number搜索，试试sonarr里标记这个剧是个动画（我记得是在添加剧集的时候可以标记）是不是有用？
> 
> 我一开始也是这样想，然而，Sonarr 电视剧根本没有绝对集数，😂

这个我知道，所以我意思是说在sonarr添加剧集的时候把Series Type设置为Anime而不是standard是不是有用？感觉可以试试……

**Comment by LuckyPuppy514** [comment]
> > > 应该是sonarr在搜动画的时候会尝试搜索多种关键字（因为动画很多是用absolute number编号的），包括 {series name} sxxexx或者 {series name} {absolute number}这些，可能普通电视剧就不会用absolute number搜索，试试sonarr里标记这个剧是个动画（我记得是在添加剧集的时候可以标记）是不是有用？
> > 
> > 
> > 我一开始也是这样想，然而，Sonarr 电视剧根本没有绝对集数，😂
> 
> 这个我知道，所以我意思是说在sonarr添加剧集的时候把Series Type设置为Anime而不是standard是不是有用？感觉可以试试……

你试试就知道了，改了也没有绝对集数，我早就试过了

**Comment by LuckyPuppy514** [comment]
![1681443903719](https://user-images.githubusercontent.com/53246532/231936655-49bc7084-16f6-45ba-b7dd-670ac48ca58d.jpg)
![image](https://user-images.githubusercontent.com/53246532/231936772-302e7a65-09eb-4ba3-b68c-defbea805d63.png)

**Comment by LuckyPuppy514** [comment]
以上是效果图，已经可以了，但是请严格按照下列说明操作：

1. 升级 JProxy 到最新版
2. 升级完建议手动同步剧集规则（定时是每天晚上同步一次）
3. Sonarr 的 Series Type 改成 Anime
![image](https://user-images.githubusercontent.com/53246532/231937082-2e5385cd-1a5e-48c0-8710-cd3e86a242a5.png)
4. 如果启用了 TMDB，建议订阅【Estab-Life: Great Escape】这部动漫，并手动同步剧集标题和TMDB标题，否则可能把这部动漫识别为重启人生
![image](https://user-images.githubusercontent.com/53246532/231937292-46500a69-60c3-49e3-8853-270bd7d6fca7.png)

**Comment by LuckyPuppy514** [comment]
关于第 4 点，同步标题后可删除 Sonarr 中的订阅，但是不要删除 JProxy 中的标题即可

**Comment by StoneShiLei** [comment]
> 关于第 4 点，同步标题后可删除 Sonarr 中的订阅，但是不要删除 JProxy 中的标题即可

感谢大佬，实测已经可以了！
顺便想问下这种电视剧用anime类型会有什么其他问题不，之前部署sonarr的时候看的教程说电视剧要用standard，只有动漫采用anime，重启人生的这个问题解决后我是不是有必要把未来需要订阅的日剧 韩剧 美剧全都改为anime类型以加强订阅搜索识别呢？

**Comment by LuckyPuppy514** [comment]
> > 关于第 4 点，同步标题后可删除 Sonarr 中的订阅，但是不要删除 JProxy 中的标题即可
> 
> 感谢大佬，实测已经可以了！ 顺便想问下这种电视剧用anime类型会有什么其他问题不，之前部署sonarr的时候看的教程说电视剧要用standard，只有动漫采用anime，重启人生的这个问题解决后我是不是有必要把未来需要订阅的日剧 韩剧 美剧全都改为anime类型以加强订阅搜索识别呢？

建议有问题再切成 Anime，一般电视剧还是首选 Standard

**Comment by StoneShiLei** [comment]
> > > 关于第 4 点，同步标题后可删除 Sonarr 中的订阅，但是不要删除 JProxy 中的标题即可
> > 
> > 
> > 感谢大佬，实测已经可以了！ 顺便想问下这种电视剧用anime类型会有什么其他问题不，之前部署sonarr的时候看的教程说电视剧要用standard，只有动漫采用anime，重启人生的这个问题解决后我是不是有必要把未来需要订阅的日剧 韩剧 美剧全都改为anime类型以加强订阅搜索识别呢？
> 
> 建议有问题再切成 Anime，一般电视剧还是首选 Standard

好的，顺便我刚部署了qbittorrent改善导入不识别的问题，就发现jproxy刚支持了transmission改名。。大佬辛苦！之前为了解决类似的问题兜兜转转了三四个月各种项目都试了，还被某国产xss坑了一百多块钱赞助费，最终还是朋友推荐我用jproxy，用了下果然解决了困扰我好久的搜索关键字识别问题，大佬有收款赞助码吗，想支持一下大佬

**Comment by LuckyPuppy514** [comment]
> > > > 关于第 4 点，同步标题后可删除 Sonarr 中的订阅，但是不要删除 JProxy 中的标题即可
> > > 
> > > 
> > > 感谢大佬，实测已经可以了！ 顺便想问下这种电视剧用anime类型会有什么其他问题不，之前部署sonarr的时候看的教程说电视剧要用standard，只有动漫采用anime，重启人生的这个问题解决后我是不是有必要把未来需要订阅的日剧 韩剧 美剧全都改为anime类型以加强订阅搜索识别呢？
> > 
> > 
> > 建议有问题再切成 Anime，一般电视剧还是首选 Standard
> 
> 好的，顺便我刚部署了qbittorrent改善导入不识别的问题，就发现jproxy刚支持了transmission改名。。大佬辛苦！之前为了解决类似的问题兜兜转转了三四个月各种项目都试了，还被某国产xss坑了一百多块钱赞助费，最终还是朋友推荐我用jproxy，用了下果然解决了困扰我好久的搜索关键字识别问题，大佬有收款赞助码吗，想支持一下大佬

我其实推荐 qb，transmission 只能重命名种子，不支持重命名文件，如果是多集，且文件命名不规范，会有问题或者得手动导入

[赞赏码在我博客，谢谢老板 🥰](https://www.lckp.top/reward)

**Comment by StoneShiLei** [comment]
> > > > > 关于第 4 点，同步标题后可删除 Sonarr 中的订阅，但是不要删除 JProxy 中的标题即可
> > > > 
> > > > 
> > > > 感谢大佬，实测已经可以了！ 顺便想问下这种电视剧用anime类型会有什么其他问题不，之前部署sonarr的时候看的教程说电视剧要用standard，只有动漫采用anime，重启人生的这个问题解决后我是不是有必要把未来需要订阅的日剧 韩剧 美剧全都改为anime类型以加强订阅搜索识别呢？
> > > 
> > > 
> > > 建议有问题再切成 Anime，一般电视剧还是首选 Standard
> > 
> > 
> > 好的，顺便我刚部署了qbittorrent改善导入不识别的问题，就发现jproxy刚支持了transmission改名。。大佬辛苦！之前为了解决类似的问题兜兜转转了三四个月各种项目都试了，还被某国产xss坑了一百多块钱赞助费，最终还是朋友推荐我用jproxy，用了下果然解决了困扰我好久的搜索关键字识别问题，大佬有收款赞助码吗，想支持一下大佬
> 
> 我其实推荐 qb，transmission 只能重命名种子，不支持重命名文件，如果是多集，且文件命名不规范，会有问题或者得手动导入
> 
> [赞赏码在我博客，谢谢老板 🥰](https://www.lckp.top/reward)

嗯，我现在已经转到qb了，transmission虽然身边几个朋友说好用，但我用起来总有零零碎碎的小问题，已经赞助大佬了，大佬加油！
