### ISSUE TITLE
反馈测试问题

### ISSUE THREAD

**Issue by 522654518** [LuckyPuppy514/jproxy#3]
大佬，您好，jproxy新版发布，第一时间前来体验了一下。
1.windows 环境报错 org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: [no body]
404 连不上
2.sonarr不仅对动画片支持不好，其实对美剧韩剧国产剧等支持的很烂，希望可以添加规则优化一下
比如 年份过滤掉  种子名字带 complete这种字符串都识别不出来
我不太会写正则表达式 希望有各位大佬加上一些新规则
3.希望设置jackett的时候带一个测试 看看能不能连上

**Comment by LuckyPuppy514** [comment]
1. 麻烦提供完整的日志信息
2. 麻烦提供几个有标志性的标题，最好是格式比较统一的
3. 只要保证你的jproxy服务器和jackett网络通就没问题了，你是windows一般就不能用127.0.0.1，建议用局域网IP

**Comment by LuckyPuppy514** [comment]
关于第3点，已经添加了简单的连通性测试和提示，预计版本v2.5.2发布
![image](https://user-images.githubusercontent.com/53246532/182055062-2cec2964-c7ca-4fc7-a887-fb40247175d2.png)
![image](https://user-images.githubusercontent.com/53246532/182055090-4ff5a08b-d177-403b-8d13-00e136d5bfe6.png)

**Comment by 522654518** [comment]
> 关于第3点，已经添加了简单的连通性测试和提示，预计版本v2.5.2发布 ![image](https://user-images.githubusercontent.com/53246532/182055062-2cec2964-c7ca-4fc7-a887-fb40247175d2.png) ![image](https://user-images.githubusercontent.com/53246532/182055090-4ff5a08b-d177-403b-8d13-00e136d5bfe6.png)

感谢大佬回复，这两天有点忙。还没仔细研究。

**Comment by 522654518** [comment]
> 1. 麻烦提供完整的日志信息
> 2. 麻烦提供几个有标志性的标题，最好是格式比较统一的
> 3. 只要保证你的jproxy服务器和jackett网络通就没问题了，你是windows一般就不能用127.0.0.1，建议用局域网IP
问题2： 比如
Better Call Saul 2020 S05 1080p BluRay x265 AAC-Auska 风骚律师第五季 这个sonarr识别不了 我觉着可能和Better Call Saul 后边的年份有关系
The Boys 2022 S03 1080p Amazon WEB-DL H264 DDP5.1-OurTV *内封简繁英多国软字幕 这个也识别不了 最好可以去掉片名之后的年份 最后这段中文我不知道会不会影响

**Comment by LuckyPuppy514** [comment]
麻烦多提供几个标志性的标题 ，最好是同一个发布组，或者同一个站，有规律的
你提供这两个看不出来有什么公共标识，虽然格式较为一致，用代码的形式提交，每行一个，一定要完整的标题
```text
Better Call Saul 2020 S05 1080p BluRay x265 AAC-Auska 风骚律师第五季
The Boys 2022 S03 1080p Amazon WEB-DL H264 DDP5.1-OurTV *内封简繁英多国软字幕
```

**Comment by 522654518** [comment]
我仔细观察了一下  如果标题 
Better Call Saul S05 1080p BluRay x265 AAC-Auska 这样的可以识别
Better Call Saul 2020 S05 1080p BluRay x265 AAC-Auska 如果是这样的就无法识别
几个美剧都是这样的  Better Call Saul 是美剧的名字   如果美剧的名字后边加了年份 sonarr就无法识别
我也不知道怎么屏蔽掉美剧后边的年份

**Comment by LuckyPuppy514** [comment]
有没有第一季的，你多提供几个标题，像我这样，用代码的形式提交，一行一个
```text
Better Call Saul 2020 S05 1080p BluRay x265 AAC-Auska
Better Call Saul 2018 1080p BluRay x265 AAC-Auska
```

**Comment by LuckyPuppy514** [comment]
可以写，你得多提交几个标题，越多就越准确，而且避免影响其他规则

**Comment by LuckyPuppy514** [comment]
标题最好是：
1. 有较为统一的格式
2. 统一格式中有细节不一样的，一个提交一个标题例子上来

**Comment by LuckyPuppy514** [comment]
QQ交流群：921905633
你有什么规则想自定义，或者想让我写的，可以群里直接说就行
最新版已经发布，新增 qBittorrent 代理，解决个别导入错误的问题，更新后记得按文档重新设置一下：[配置文档 - v2.6.0](https://github.com/LuckyPuppy514/jproxy/blob/main/README.zh_CN.md#2-%E9%85%8D%E7%BD%AE)
这个问题我就先关闭了
