### ISSUE TITLE
重新安装最新版 docker，Sonarr连接Qb出现问题。

### ISSUE THREAD

**Issue by casselluu** [LuckyPuppy514/jproxy#30]
IP没问题，使用8117端口，sonarr连通性测试失败。使用8080直连qb成功
JProxy日志：
ERROR [xec-5] jproxy.service.impl.SystemUserServiceImpl.verify(SystemUserServiceImpl.java:113) : invalid token: The token was expected to have 3 parts, but got 0.

**Comment by LuckyPuppy514** [comment]
你是不是没看变更日志，新版本 qBittorrent 设置，不需要在 Sonarr 设置了，但是要填写账号密码
先自己看下文档：[wiki](https://github.com/LuckyPuppy514/jproxy/blob/main/wiki.md#qbittorrent)

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/232177411-7909534f-b826-4459-97ea-3df4c27819d7.png)

**Comment by casselluu** [comment]
> 你是不是没看变更日志，新版本 qBittorrent 设置，不需要在 Sonarr 设置了，但是要填写账号密码 先自己看下文档：[wiki](https://github.com/LuckyPuppy514/jproxy/blob/main/wiki.md#qbittorrent)

主要是在设置界面只有qb地址，没有账号密码输入的位置

**Comment by LuckyPuppy514** [comment]
应该是有浏览器缓存，`CTRL + F5` 强制刷新一下应该就会出来了

**Comment by casselluu** [comment]
> 应该是有浏览器缓存，`CTRL + F5` 强制刷新一下应该就会出来了

手动指定v3.1.6后出现了，之前latest应该不知为何没更新到最新版。
