### ISSUE TITLE
sonarr标题搜索问题

### ISSUE THREAD

**Issue by su2do** [LuckyPuppy514/jproxy#32]
1、剧集&动漫 标题中含有  单词"the"  符号 ' ，会导致报错 找不到匹配的标题
![图片](https://user-images.githubusercontent.com/6203805/232291222-855a827d-8622-4722-9af0-66082305cb41.png)
![图片](https://user-images.githubusercontent.com/6203805/232291233-46a39cff-4f8d-4d7c-8b92-c0f98aafb8f4.png)
![图片](https://user-images.githubusercontent.com/6203805/232291258-5da13088-f277-43cb-b1e7-d2b035401fd3.png)
以上三个完整标题为  The Mandalorian   Hell's Paradise  The Dangers in My Heart 由于此报错导致sonarr完全搜索不到结果。

2、sonarr 动漫第二季 搜索时 会使用 类似 冰海战记 S02E14 或 冰海战记 38 进行搜索，但是动漫资源站点命名方式均不标准，导致所有动漫第二季无法搜索到解决
建议同时拦截搜索的  title season episode
![图片](https://user-images.githubusercontent.com/6203805/232291640-b31dc199-cabd-4004-8d88-591b0db8a2e2.png)
![图片](https://user-images.githubusercontent.com/6203805/232291679-9f9a1263-1b40-4c59-b53c-a51fef176e38.png)

【悠哈璃羽字幕社】[海盗战记/冰海战记_Vinland Saga S02][14][x264 1080p][CHT] 
[ANi] 机动战士钢弹 水星的魔女 Season 2 - 14 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4]

**Comment by LuckyPuppy514** [comment]
1. 第一个问题，jproxy 无法匹配到主标题，只会影响追加 TMDB 标题进行搜索，绝大部分情况都不会有问题，完全可以不用管，你搜索不到结果，估计也是由于第二个问题导致的；
2. 第二个问题，明显你的 Sonarr 设置有问题，动漫不应该用 S02E14 这种格式搜索，这明显是 Series Type 为 Standard 的搜索格式
![image](https://user-images.githubusercontent.com/53246532/232327277-8f494d2d-0ef4-4e58-b7bb-8528a63cef32.png)

请检查 Sonarr 以下设置，避免无法搜索到结果
1. Series Type，电视剧选择 Standard，动漫选择  Anime
![image](https://user-images.githubusercontent.com/53246532/232327422-eb00c583-32ec-46b7-b77a-014f32bb1cf9.png)

2. 确保你的 Sonarr 能正确获取动漫绝对集数，季数，季标题等信息
![20230417004326](https://user-images.githubusercontent.com/53246532/232327509-0d3465d8-4840-44d6-9c92-5b11d4f68ce5.gif)
正常应如上图所示，鼠标放上去会显示，如果没有显示
① 请尝试删除后重新添加改剧
② 请确保可科学上网，并确保 Sonarr 服务器，可访问：[https://thexem.info](https://thexem.info)，可通过以下命令测试
```bash
curl https://thexem.info
```
正常应该如下图所示
![20230417004803](https://user-images.githubusercontent.com/53246532/232327712-bf11410d-013b-41eb-8f7a-eaa313494210.gif)
如果可以科学上网，却无法访问改网址，可手动添加域名 `thexem.info` 到科学上网软件或插件的代理列表中（各软件和插件设置有差异，请自行上网查阅相关设置）

3. 请确保你的索引器设置正确，注意 Categories 和 Anime Categories 的选择，第一步中 Series Type 为 Standard 会用 Categories 中的分类进行搜索，为 Anime 则会使用 Anime Categories 的分类进行搜索
![image](https://user-images.githubusercontent.com/53246532/232327764-1283e297-dbba-482d-a4a9-c2cb39c059c5.png)

最后，你如果刚开始玩，或者有条件可以创建虚拟机，可尝试部署这个项目：[https://github.com/LuckyPuppy514/automatic-theater](https://github.com/LuckyPuppy514/automatic-theater)
所有系统的设置都是我个人设置好的，只要保证科学上网，一般就不会有问题，同时你也可以参考里面各个系统的设置

**Comment by su2do** [comment]
1、第一点也是因为没有使用追加的 TMDB 标题 搜索 并且拦截删除了 标题中  “the” 单词而导致搜索不到内容
![图片](https://user-images.githubusercontent.com/6203805/232328708-23f2c9c9-f115-4d6a-a6ce-982436b2b09d.png)

2、我sonarr中anime的分类是对的，现在识别不了第二季也是因为sonarr对于动漫第二季的绝对集数是错误的，例如图中冰海战记第二季14集 搜索的绝对集数内容 是 冰海战记 38（第一季 24+第二季14），但是现在动漫站均不是这样命名的
![图片](https://user-images.githubusercontent.com/6203805/232328266-9d4255cf-d7ac-4744-a0ee-d2886e2453e7.png)
![图片](https://user-images.githubusercontent.com/6203805/232328536-75bf5711-f998-48ca-aa8f-b1e5c1557599.png)

**Comment by LuckyPuppy514** [comment]
大哥，我求求你认真看我的回复，the 并不是 jproxy 去掉的，jproxy 的 error 无法匹配标题，只是说 jproxy 无法匹配到对应标题，从而无法追加对应的 TMDB 标题去搜索，不会影响正常搜索

**Comment by LuckyPuppy514** [comment]
如果你 Series Type 是 Anime，那么你可能开启了这个设置，我不建议开启，建议你看完我说的设置，主要是确保能正确获取到绝对集数，季数，季标题
![image](https://user-images.githubusercontent.com/53246532/232328971-cfda6a04-2b77-4cef-af78-98e323933e0a.png)

**Comment by LuckyPuppy514** [comment]
我回复中，最重要的两个点
 - Series Type
 - 正确获取动漫绝对集数，季数，季标题等信息，能访问：[thexem.info](https://thexem.info/)
但是你根本没有确认第二点（第二点特别重要，我已经见过N多人无法搜索到结果就是由于这个原因，并且开启 Anime Standard Format Search 是治标不治本的办法，我不推荐）
我花时间回复了，也请你花时间认真看完回复，做完测试有问题再继续追问

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/232329479-10d3cc11-0f53-4661-a5e2-cb5b5e715778.png)
![image](https://user-images.githubusercontent.com/53246532/232329491-87eaf1e0-141a-4a9a-8b55-bdbbf8b72df1.png)

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/232329520-20559d0e-49f5-4fc3-bb3e-75c359584ecb.png)

**Comment by su2do** [comment]
1、重新测试了下，the 是sonarr去掉的
2、我按照你图中的设置去除了  Anime Standard Format Search 设置，也验证了  能访问：[thexem.info](https://thexem.info/)  但是仍然解决不了搜索不到动漫第二季的问题


![图片](https://user-images.githubusercontent.com/6203805/232329880-c7f0d9cb-8b36-41c0-aa6f-d7d357a910ac.png)
![图片](https://user-images.githubusercontent.com/6203805/232329888-f7af5e69-1daa-4039-a24c-e3b90faebf18.png)
![图片](https://user-images.githubusercontent.com/6203805/232329912-b981d8b8-0a3e-4ee9-9b90-e760ae668b7a.png)
![图片](https://user-images.githubusercontent.com/6203805/232329933-f8932ed7-aeb1-49d9-afd7-c83a672f9f0b.png)
![图片](https://user-images.githubusercontent.com/6203805/232329945-d19f87e6-035b-4a89-88f4-f9b305b39452.png)
用蜜柑计划举例如上

**Comment by LuckyPuppy514** [comment]
大哥，最重要的，你都漏了
![](https://user-images.githubusercontent.com/53246532/232327509-0d3465d8-4840-44d6-9c92-5b11d4f68ce5.gif)

**Comment by LuckyPuppy514** [comment]
你的只会用 38 搜索，明显是由于没有获取到上图中的信息

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/232330109-3c2ad55a-c3e0-4a5a-88c0-0197593cb1f0.png)

**Comment by LuckyPuppy514** [comment]
我真的请你认真看回复，认真检查我说的每一个细节，因为每一个细节的设置都有可能影响搜索结果，当初我也是花了很多时间自己折腾出来的经验 🥲

**Comment by su2do** [comment]
不好意思，我大概找到问题了，应该是我用的sonarr版本有问题，我现在用的群晖套件版，我用回老的docker版本测试就没问题了。设置都是一模一样的

**Comment by LuckyPuppy514** [comment]
这个问题跟设置关系不大，大部分是网络问题（不能访问：[thexem.info](https://thexem.info)），其次可能是群晖 sonarr 版本问题，好像前几天也有个人也是换成 docker 版就可以了
![](https://user-images.githubusercontent.com/53246532/232327509-0d3465d8-4840-44d6-9c92-5b11d4f68ce5.gif)
PS：你按照我一开始说的检查一遍，其实马上就能找到问题的 😂

**Comment by LuckyPuppy514** [comment]
上面这个 gif 图片展示的信息，对动漫搜索至关重要，你原来可能可以搜到一些，是因为开启了下图的设置
![](https://user-images.githubusercontent.com/53246532/232328971-cfda6a04-2b77-4cef-af78-98e323933e0a.png)
还是强调一遍，这个设置治标不治本，因为绝大部分的动漫发布组，都不会用 S02E14 这种格式（PT发布组可能会）

**Comment by su2do** [comment]
我在检查群晖的网络，应该是没有成功调用代理。  Anime Standard Format Search 我都去掉了

**Comment by Archer-Tatsu** [comment]
提供个思路，thexem.info貌似屏蔽了大陆ipv6地址（至少我这边是访问不了的），然后我梯子挂路由器上貌似会放行全部ipv6请求（都不代理）。猜想lz跟我同样的情况。群晖套件应该是直接走的群晖host网络，可能也有类似的问题，而docker里如果用桥接网络的话默认应该是关ipv6的

**Comment by su2do** [comment]
的确是的，关闭了群晖的IPV6就OK了

**Comment by LuckyPuppy514** [comment]
😂 网络环境，各个系统设置等这里就不讨论了，比较复杂，细微之处都可能导致各种问题，有兴趣可以加Q群探讨：`921905633`

PS：开源不易，好用的话麻烦点下右上角的小星星 🌟，谢谢 🙏
