### ISSUE TITLE
在WebUI配置网络代理

### ISSUE THREAD

**Issue by BopohoN** [LuckyPuppy514/jproxy#33]
TMDB的配置总是连不上，用HTTP_PROXY和HTTPS_PROXY的环境变量都没有办法连通代理，但是curl themoviedb.org是有返回的，不知道可不可以直接在webUI里设置网络代理

**Comment by LuckyPuppy514** [comment]
1. 环境变量是不行的
2. 当前建议采用网关的方式科学上网
3. 后续可能会考虑添加代理设置

**Comment by BopohoN** [comment]
好的，原来如此

**Comment by BopohoN** [comment]
测试了一下，进入容器内修改hosts指定tmdb的网址是可以连上的，先这样用吧

**Comment by LuckyPuppy514** [comment]
> 测试了一下，进入容器内修改hosts指定tmdb的网址是可以连上的，先这样用吧

改 HOST 或者设置环境变量，客户端等方式代理我个人都比较不推荐，我其实是推荐网关设置为OP的方式科学上网，简单而且确保所有程序都能走代理，玩这一套没有科学就非常多坑，具体可以参考我另外一个项目的说明：[automatic-theater](https://github.com/LuckyPuppy514/automatic-theater#-3-%E7%BD%91%E7%BB%9C)

**Comment by LuckyPuppy514** [comment]
> 测试了一下，进入容器内修改hosts指定tmdb的网址是可以连上的，先这样用吧

我测试了一下，直接在 JAVA_OPTS 添加代理参数即可，例如

http 代理，ip 为 `192.168.6.2`，端口号为 `123456`

```text
version: '3.0'
services:
   jproxy:
      image: luckypuppy514/jproxy:latest
      container_name: jproxy
      restart: unless-stopped
      environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx512m -Dhttp.proxyHost=192.168.6.2 -Dhttp.proxyPort=12345
      ports:
      - 8117:8117
      volumes:
      - /docker/jproxy/database:/app/database
```

socks 代理，ip 为 `192.168.6.2`，端口号为 `54321`

```text
version: '3.0'
services:
   jproxy:
      image: luckypuppy514/jproxy:latest
      container_name: jproxy
      restart: unless-stopped
      environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx512m -DsocksProxyHost=192.168.6.2 -DsocksProxyPort=54321
      ports:
      - 8117:8117
      volumes:
      - /docker/jproxy/database:/app/database
```

**Comment by QYG2297248353** [comment]
我更希望，能增加 WebUI 配置代理，修改环境变量，操作难度有点高。能够类似 sonarr 在设置中决定是否启用代理
不知道，后续会不会考虑
