### ISSUE TITLE
搜索词只能改标题名，没法把标题后面的季或者集也改掉

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#34]
我用了一段时间新版，搜索词好像只能改标题名，没法把标题后面的季或者集也改掉，这个功能我感觉很多场景还是能用到的。

比如sonarr在选择standed的情况下是无法搜索到xxx 01这样的剧集的，即standed下无法自动追动漫番剧， 但只需要把xxx S01E01这样的搜索词匹配下，比如这样匹配下(.*)\sS\d+E(\d+)，然后S01E01替换成01，standed模式就可以实现自动追剧了。这样就不用standed和anime切换了。

如果有需要，我还可以列出好几个应用场景。

**Comment by LuckyPuppy514** [comment]
首先，我大概理解你的意思，你是想用统一使用 Standard ，去除搜索中的 S01E01 或 改成 01 去搜索，既支持追电视剧，又支持追动漫，但是，这样并不好，有问题你根本没考虑到，而且 Sonarr 有这种分类是有道理的
1. 只要你使用 jellyseerr / overseerr / ombi 这类系统，Series Type 会自动根据类型选择 Anime / Standard
2. 即使是手动选择，你也应该合理的选择，电视剧 - Standard，动漫 - Anime，这是普遍适用的规则，而不是为了方便随意选择或者固定选择一个
3. Standard 会使用 S01E01 格式，和索引器中 Categories 分类去搜索，Anime 会使用季标题+相对集数，或绝对集数，和索引器 Anime Categories 分类进行搜索，而且都普遍适用的规则，大部分发布组都遵循这样的规则
4. 如果采用你说的方式，每个搜索都会增加很多无意义的搜索，比如电视剧会用动漫分类搜索，比如 S02E01 会用 01 搜索，但是少了 S02 限制，再比如，动漫有季标题，如果用 standard 并不会使用季标题搜索等等，这样会产生一系列的问题
5. 另外，你可以看下这个 [issue](https://github.com/LuckyPuppy514/jproxy/issues/32) 

总之，并不是你想象中的那么简单，建议加Q群沟通：921905633，我给你好好解释，这里一时半会说不完 😂
