### ISSUE TITLE
能否增加针对tmbd剧集“别名”的中文搜索

### ISSUE THREAD

**Issue by maodun96** [LuckyPuppy514/jproxy#35]
能否增加针对tmbd剧集“别名”的中文搜索

**Comment by LuckyPuppy514** [comment]
目前有需要可以自行修改 TMDB 同步的标题，同时用于搜索和匹配

![image](https://user-images.githubusercontent.com/53246532/235330218-f6a04817-fff8-4ea9-9d94-00f94c88b0d5.png)

**Comment by maodun96** [comment]
> 目标之前有需要可以自行修改TMDB同步的标题，同时用于搜索和匹配
> 
> ![图像](https://user-images.githubusercontent.com/53246532/235330218-f6a04817-fff8-4ea9-9d94-00f94c88b0d5.png)

该列表的条目似乎需要满足此条件：TMDB上，剧集关联了TVDB ID外部编号。
这个条件感觉会造成一定限制，能否表单TVDB ID值留空，仅呈现TMDB上的多种翻译。

**Comment by LuckyPuppy514** [comment]
v3.2.1 新增了一个标题新增的功能，有需要可以自行添加别名

![image](https://user-images.githubusercontent.com/53246532/235338564-4100853d-9962-4c80-9a70-bc148a42df1a.png)
