### ISSUE TITLE
能否增加Standard类型的仅中文名搜索？

### ISSUE THREAD

**Issue by maodun96** [LuckyPuppy514/jproxy#37]
因为存在一种情况，仅依靠中文剧名搜索(不包含S1E1等信息)，索引器返回jproxy代理后的发布，再与具体剧集匹配。
而通过  XXX.S1或XXX.S1E1 则不一定返回发布。
例子：日剧Mr. Bride, My Darling。增加自定义标题“我的媳夫”后，匹配btdigg索引的other分类。standard类型无返回发布，anime类型有返回发布，**实际上有意义的是搜索“我的媳夫”返回的结果**。(图中重复索引是因为添加了一个未过jproxy的)
![image](https://user-images.githubusercontent.com/43996175/236637169-a387cadf-0a33-4551-b77e-a67461d83c20.png)
![image](https://user-images.githubusercontent.com/43996175/236637623-2a50341d-8adb-4429-82fb-4707f69227b4.png)
具体种子名是
【高清剧集网 www.BTHDTV.com】我的媳夫[第04集][中文字幕].Watashi.no.Oyome-kun.2023.S01.1080p.KKTV.WEB-DL.x264.AAC-Huawei
【高清剧集网 www.BTHDTV.com】我的媳夫[第04集][中文字幕].Mr.Bride.My.Darling.S01.1080p.KKTV.WEB-DL.AAC2.0.H.264-KKTV

改anime类型的话，要改jellyseerr添加剧集的类型。也要勾选索引器的Anime Standard Format Search设置。感觉有点乱。 
只增加中文剧名的搜索也可以仅适配国内发布组的命名。也不会有过多的无意义搜索结果。

已看过这两个issues，适用场景重复于第一个ssues，需求部分重复于第二个issues。
#28 
#34

**Comment by LuckyPuppy514** [comment]
很多发布组把日剧当成 anime 发布的，所以暂时还是建议 series type 改成 anime
至于 Anime Standard Format Search 没必要勾选，我个人也不建议勾选

**Comment by maodun96** [comment]
> 很多发布组把日剧当成 anime 发布的，所以暂时还是建议 series type 改成 anime 至于 Anime
> Standard Format Search 没必要勾选，我个人也不建议勾选
动漫网站包含的一般是MagicStar的无字幕版本。上述建议其实主要针对的是高清剧集网重新加字幕打包的种子。
这种种子往往出现在综合BT站里面，而他们一般也被分为other分类。所以如果类型选成anime的话，Standard Format Search也有必要勾选了。

**Comment by maodun96** [comment]
> 很多发布组把日剧当成 anime 发布的，所以暂时还是建议 series type 改成 anime
> 至于 Anime Standard Format Search 没必要勾选，我个人也不建议勾选

动漫网站包含的一般是MagicStar的无字幕版本。上述建议其实主要针对的是高清剧集网重新加字幕打包的种子。
这种种子往往出现在综合BT站里面，而他们一般也被分为other分类。所以如果类型选成anime的话，Standard Format Search也有必要勾选了。

**Comment by LuckyPuppy514** [comment]
Standard Format Search 没必要勾选，除非有下列相对集数和绝对集数信息，否则全部都会用：`标题 00` 搜索，JProxy 会去除 00

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/54a3ea45-ab87-4230-bc03-b2b6ae3aadf4)

**Comment by LuckyPuppy514** [comment]
真的没必要勾选 Standard Format Search

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/cfccca5a-380d-4792-a94e-b7560b0373dc)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/6f874570-ec34-4780-a9e4-54d0996f3cbf)

**Comment by maodun96** [comment]
> 

是的，没必要勾选。之前不勾选搜索不到的情况可能是索引故障导致的。

**Comment by maodun96** [comment]
@LuckyPuppy514 
观察到一个有意思的情况。
按sonarr自动化的逻辑：多次抓取索引后再匹配剧集。
当在Standard模式下，手动搜索季度或单集结果皆为空。因为搜索的名字包含S1E1之类的信息。
![image](https://github.com/LuckyPuppy514/jproxy/assets/43996175/b76d3481-6e62-401d-ba4b-b9bedbb98fa0)

但是每次自动更新会抓取jproxy代理后的名字，并且匹配到单集后下载。
![image](https://github.com/LuckyPuppy514/jproxy/assets/43996175/7fd9009a-46b4-493e-ad3e-1d32e6256e76)

观察到的例子是Kitchen Knife and Green Chili Pepper日剧。

**Comment by LuckyPuppy514** [comment]
这个是正常现象，手动搜索是携带关键词去搜索，可能搜不到这条记录，但是RSS定时更新是没有关键词的，只要是最近发布的都会搜索到

**Comment by maodun96** [comment]
> 这个是正常现象，手动搜索是携带关键词去搜索，可能搜索不到这条记录，但是RSS定时更新是没有关键词的，只要是最近发布的都会搜索到

了解，只是体验有些割裂。感觉纯中文名搜索还是有一定的必要。

**Comment by LuckyPuppy514** [comment]
v3.2.2 已添加

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/ed3eb69f-daa4-4af1-b838-9a875f49970d)

**Comment by maodun96** [comment]
> v3.2.2 已添加
> 
> ![image](https://user-images.githubusercontent.com/53246532/240090954-ed3eb69f-daa4-4af1-b838-9a875f49970d.png)

牛的 感谢
