### ISSUE TITLE
qbittorrent被修改文件名后 无法通知到sonarr

### ISSUE THREAD

**Issue by CoderYqq** [LuckyPuppy514/jproxy#40]
我的模式为 prowlarr→Jproxy→sonarr→qBittorrent
Jproxy已正确配置prowlarr和sonarr及qBittorrent地址
sonarr已正确配置prowlarr索引地址链接

手动订阅Demon Slayer: Kimetsu no Yaiba(鬼灭之刃第四季)剧集 第7集细节如下:
1.测试资源原始文件名:[织梦字幕组][鬼灭之刃 锻刀村篇 鬼滅の刃 刀鍛冶の里編][07集][1080P][AVC][简日双语]
2.Jproxy经过配置后格式化文件名:Demon Slayer: Kimetsu no Yaiba[S4E7][简日][1080P][-织梦字幕组]
3.sonarr能正确识别并将下载任务发送到qBittorrent,下载的文件名为种子原始文件名
4.Jproxy立马将qBittorrent的原始文件名更名为格式化后名称

问题:由于qbittorrent被更名 sonarr貌似无法将任务添加到下载队列中 qbt下载完毕后也无法通知sonarr重命名且移动文件

以下为sonarr日志:
[Info] ReleaseSearchService: Searching indexers for [Demon Slayer: Kimetsu no Yaiba : S04E07]. 3 active indexers 
[Info] DownloadDecisionMaker: Processing 2 releases 
[Info] EpisodeSearchService: Episode search completed. 0 reports downloaded. 
[Info] ReleaseSearchService: Searching indexers for [Demon Slayer: Kimetsu no Yaiba : S04E07]. 4 active indexers 
[Info] DownloadDecisionMaker: Processing 42 releases 
[Info] DownloadService: Report sent to qBittorrent. Indexer ACGsou (Jproxy). Demon Slayer: Kimetsu no Yaiba[S4E7][简日][1080P][-织梦字幕组] 
[Info] EpisodeSearchService: Episode search completed. 1 reports downloaded.

Jproxy日志:
11:30:50.508 INFO  [xec-5] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:154)    : qBittorrent 文件重命名成功：[织梦字幕组][鬼灭之刃 锻刀村篇 鬼滅の刃 刀鍛冶の里編][07集][1080P][AVC][简日双语].mp4 => S4E7.mp4
11:30:50.509 INFO  [xec-5] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:158)    : qBittorrent 种子重命名成功：808addd66dbe76392c2fae690c376d018c593113 => Demon Slayer: Kimetsu no Yaiba[S4E7][简日][1080P][-织梦字幕组]
11:31:14.512 ERROR [xec-4] com.lckp.jproxy.util.CheckUtil.checkTmdbApi(CheckUtil.java:156)                  : TMDB URL 无效：I/O error on GET request for "https://api.themoviedb.org/3/movie/550": Connect timed out
11:42:00.011 INFO  [ing-1] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:154)    : qBittorrent 文件重命名成功：[织梦字幕组][鬼灭之刃 锻刀村篇 鬼滅の刃 刀鍛冶の里編][07集][1080P][AVC][简日双语].mp4 => S4E7.mp4
11:42:00.068 INFO  [ing-1] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:158)    : qBittorrent 种子重命名成功：808addd66dbe76392c2fae690c376d018c593113 => Demon Slayer: Kimetsu no Yaiba[S4E7][简日][1080P][-织梦字幕组]

**Comment by CoderYqq** [comment]
补充下前面sonarr日志是没有开启重命名的  开启后依然提示0文件导入 实际qbt已经下载成功
[Info] ImportListSyncService: Starting Import List Sync 
[Info] ImportListSyncService: Processing 0 list items 
[Info] ImportListSyncService: Import List Sync Completed. Items found: 0, Series added: 0

**Comment by LuckyPuppy514** [comment]
看你的问题，应该是说抓取后，qBittorrent 开始下载，但是下图中的队列即使刷新也不显示，我也遇到过这个问题，这是 Sonarr 抽风了，重启 Sonarr 一般就没问题了 （偶发性问题，Sonarr 好像有人提这个 issue 但是我现在没关注了，反正我遇到了重启基本上很久都不会再遇到）

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/6ed67331-43c6-48df-9e5c-4a846336389f)

**Comment by LuckyPuppy514** [comment]
> 看你的问题，应该是说抓取后，qBittorrent 开始下载，但是下图中的队列即使刷新也不显示，我也遇到过这个问题，这是 Sonarr 抽风了，重启 Sonarr 一般就没问题了 （偶发性问题，Sonarr 好像有人提这个 issue 但是我现在没关注了，反正我遇到了重启基本上很久都不会再遇到）
> 
> ![image](https://user-images.githubusercontent.com/53246532/241558972-6ed67331-43c6-48df-9e5c-4a846336389f.png)

另外，Sonarr 跟 qBittorrent 是通过种子 HASH 和种子分类确定下载的文件的，重命名不会影响

**Comment by CoderYqq** [comment]
@LuckyPuppy514 感谢回复  我试过更新sonarr和qbt的版本后发现正常了 确实是sonarr的问题
