### ISSUE TITLE
规则错误

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#42]
Codenamed Vicious Dog被识别为Vicious

**Comment by PN62323424** [comment]
同理the condor heroes被识别为heroes

我估计这种错误还有很多很多，提取title的默认规则是不是应该改一下

**Comment by LuckyPuppy514** [comment]
暂时没找到很好的办法分离出标题，现在都是通过包含净标题的方式判断是哪一部剧，这就会导致你说的问题
目前的解决办法是把混淆的剧集也订阅了，这样就不会识别错误，或者手动加个规则

**Comment by LuckyPuppy514** [comment]
你没理解我说的，现在的问题是，没有一个很好的办法从原始发布的标题中提取出剧集标题（就是你说的未格式化的标题）

**Comment by PN62323424** [comment]
嗯，我前面理解错了。

如果不考虑动漫及the被去掉的情况，其实可以从开头匹配就没事了，像pt站的都是标题写最前面的

**Comment by LuckyPuppy514** [comment]
> 嗯，我前面理解错了。
> 
> 如果不考虑动漫及the被去掉的情况，其实可以从开头匹配就没事了，像pt站的都是标题写最前面的

你还是没理解，你这两个例子跟 the 去不去掉没有任何关系

**Comment by PN62323424** [comment]
我当然知道跟the没关系，我只是说如果从开头匹配就跟the有关系了

**Comment by LuckyPuppy514** [comment]
当前逻辑大致逻辑是
1. 同步 Sonarr 已经订阅剧集的标题到 JProxy
2. 用查询到的原始信息，判断是否含有 1 中的标题，有则认为是该剧集（例如，订阅了 Heroes，查询到 the condor heroes S01E01，包含 heroes 所以被判断为 heroes）

**Comment by LuckyPuppy514** [comment]
> 我当然知道跟the没关系，我只是说如果从开头匹配就跟the有关系了

开头，你说的开头怎么判断？

**Comment by PN62323424** [comment]
^净标题这样开始匹配title，但动漫这样就不好解决了

**Comment by LuckyPuppy514** [comment]
1. 你要先清楚，已知条件是 heroes ，而 the condor heroes 是未知的，当前程序无法知道有这部剧，除非你订阅了
2. 你说的开头，例如 PT 很多剧集放在开头，然而，即使是 PT 你都不敢保证 100%，而 BT 中，尤其是动漫，绝大部分标题都不在开头，发布的原始标题，除了同一个发布组可能有较为固定的格式（有时同一个发布组也会有各种各样的格式），所以我前面说了，暂时没有很好的办法提取原始信息中的标题

**Comment by LuckyPuppy514** [comment]
1. 你要先清楚，已知条件是 heroes ，而 the condor heroes 是未知的，当前程序无法知道有这部剧，除非你订阅了
2. 你说的开头，例如 PT 很多剧集放在开头，然而，即使是 PT 你都不敢保证 100%，而 BT 中，尤其是动漫，绝大部分标题都不在开头，发布的原始标题，除了同一个发布组可能有较为固定的格式（有时同一个发布组也会有各种各样的格式），所以我前面说了，暂时没有很好的办法提取原始信息中的标题

**Comment by LuckyPuppy514** [comment]
按照你的逻辑，假设原始信息：the condor heroes S01E01，heroes 从头开始匹配，当前结果为不匹配，那么我要不要继续原来的逻辑匹配呢？
1. 不继续匹配，那么就会导致，绝大部分数据都不会匹配
2. 继续匹配，那么还是会匹配成 heroes

**Comment by PN62323424** [comment]
> 按照你的逻辑，假设原始信息：the condor heroes S01E01，heroes 从头开始匹配，当前结果为不匹配，那么我要不要继续原来的逻辑匹配呢？
> 
> 1. 不继续匹配，那么就会导致，绝大部分数据都不会匹配
> 2. 继续匹配，那么还是会匹配成 heroes

我只是讨论下，当前确实没更好的办法了。或者能预置所有剧集的标题正则就好了

**Comment by LuckyPuppy514** [comment]
1. 我只能说，我当前能力有限，想不出什么很好的办法，如果我想到了，且有时间，我就会尽力优化
2. 或者你有什么好的办法，可以提出来，不过提之前，我建议你理清 Sonarr 和 JProxy 的逻辑，以及先考虑下方案的通用性，可行性（比如你说的，预设所有剧集标题，就基本上不具备可行性），我没办法一个一个解释

**Comment by PN62323424** [comment]
你指望每个用户对sonarr及jproxy达到你的水准才能提issue这个怎么可能，我提之前当然也尽量考虑了下可实现情况。

**Comment by LuckyPuppy514** [comment]
1. 我没说一定要达到什么程度才可以提 issue，我只是建议
2. 我前面已经回复了，暂时没有更好的办法

**Comment by LuckyPuppy514** [comment]
[v3.2.5](https://github.com/LuckyPuppy514/jproxy/commit/5fb0dd090883be047dcd2643efc8154048acfc9a) 针对单个英文单词标题匹配做了优化，类似 The Condor Heroes 这种标题不会被匹配成 Heroes 了

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/5749d93c-53e7-4ea1-b62b-f053ef10f45b)
