### ISSUE TITLE
可否纯标题提搜索,在返回结果中二次匹配季,集?

### ISSUE THREAD

**Issue by weigeloveu** [LuckyPuppy514/jproxy#43]
**问题描述**
有很多剧集的发布名字很乱,如果加了季跟集会导致jackett搜索不到.可否纯标题提搜索,在返回结果中二次匹配季,集?
比如说这个剧集,只用中文名或者英文名搜索都可以搜到完整的结果
<img width="1123" alt="截屏2023-06-03 19 43 06" src="https://github.com/LuckyPuppy514/jproxy/assets/19830500/f4def687-b26f-41b9-a701-9e174469fd9d">
但是sonarr的搜索会自动加入季跟集,比如说,第八集,发到jackett的标题加了s1e08,这样肯定是搜索不到的
<img width="950" alt="截屏2023-06-03 19 46 42" src="https://github.com/LuckyPuppy514/jproxy/assets/19830500/94b81447-b6fb-4039-beaa-cde8444b9051">

**功能描述**

可否纯标题提搜索,在返回结果中二次匹配季,集?
还是这个剧集打比方,在所有的结果中二次筛选,jackett这边可以二次筛选,具体有没有接口就不知道了,小白不懂代码....
<img width="1194" alt="截屏2023-06-03 19 51 11" src="https://github.com/LuckyPuppy514/jproxy/assets/19830500/a53c17d5-b79d-4f10-b56e-caf6b80e1066">
或者所有的结果抓到jproxy里边进行处理,筛选出第八集的链接再发给sonarr

**Comment by LuckyPuppy514** [comment]
1. 已经有该功能，见 #37
2. 亲测没问题，自行检查是否升级到最新版，有问题手动同步标题+清除所有缓存

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/e25a439f-37c0-461c-8f4e-21651eba2430)

**Comment by weigeloveu** [comment]
> 1. 已经有该功能，见 [能否增加Standard类型的仅中文名搜索？ #37](https://github.com/LuckyPuppy514/jproxy/issues/37)
> 2. 亲测没问题，自行检查是否升级到最新版，有问题手动同步标题+清除所有缓存
> 
> ![image](https://user-images.githubusercontent.com/53246532/243092984-e25a439f-37c0-461c-8f4e-21651eba2430.png)

感谢大佬,这个功能是怎么用呢,为啥我在sonarr里边点搜索,在log中搜索的关键词都是代季跟集的,是哪里姿势不对吗?

**Comment by LuckyPuppy514** [comment]
开启 [TMDB](https://github.com/LuckyPuppy514/jproxy/wiki#tmdb) 功能或手动添加 TMDB 标题
当 `标题 S01E01` 格式搜索结果较少时，会自动追加 `主语言标题` 搜索

**Comment by weigeloveu** [comment]
<img width="1044" alt="截屏2023-06-03 21 30 30" src="https://github.com/LuckyPuppy514/jproxy/assets/19830500/db01ae9f-3f6c-48a9-ae99-3cecdac19519">
<img width="1071" alt="截屏2023-06-03 21 30 48" src="https://github.com/LuckyPuppy514/jproxy/assets/19830500/cd6954ff-ffff-4fde-868e-b443cd009116">
这算开启了吗?我在sonarr里边点小人,搜索结果只有5集,但是“search monitored”会自动添加1-8(第三集没有),很奇怪

**Comment by LuckyPuppy514** [comment]
看你日志不是已经追加了 `即使你不和我做` 搜索了么

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/fed46504-2e03-4b72-8b03-2b7ee54e351c)

但是你想要搜索的是 `我们之间没有的`

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/5f3331c1-7989-4e13-a038-2c91832c8502)

你需要自己手动修改标题，注意，追加的是主语言标题

**Comment by weigeloveu** [comment]
<img width="834" alt="截屏2023-06-03 21 37 50" src="https://github.com/LuckyPuppy514/jproxy/assets/19830500/2c2fb272-6f9e-4935-9148-878857bcfe37">
这个就是我手动添加的....(顺便问一下大佬用的哪个引擎,结果好多....)
我过滤这个Audiences咋就毛都没有....
<img width="807" alt="截屏2023-06-03 21 40 26" src="https://github.com/LuckyPuppy514/jproxy/assets/19830500/3b451bd8-5802-4484-a1bf-ffb25b5b92e0">

**Comment by LuckyPuppy514** [comment]
我建议你先自行理清 Sonarr 的搜索逻辑，看你的日志截图，JProxy 是正常追加了主语言标题搜索的，
至于搜索到什么结果，跟关键字，分类，索引器都有关系，如果 Sonarr 跟 Jackett 直接搜索不一样，请自行对比搜索条件，大概率是你自己手动搜索的条件不一致（比如，根据你上述描述，你手动搜索的明显是 `我们之间没有的`，但是 JProxy 追加的是主语言标题 `即使你不和我做`，你添加的主语言标题不对该规则生效，因为主语言标题也只会取一个，你要就把 `即使你不和我做` 修改成其他语言，或者删除）

**Comment by weigeloveu** [comment]
懂了,感谢大佬教导

**Comment by LuckyPuppy514** [comment]
> <img alt="截屏2023-06-03 21 37 50" width="834" src="https://user-images.githubusercontent.com/19830500/243097683-2c2fb272-6f9e-4935-9148-878857bcfe37.png"> 这个就是我手动添加的....(顺便问一下大佬用的哪个引擎,结果好多....) 我过滤这个Audiences咋就毛都没有.... <img alt="截屏2023-06-03 21 40 26" width="807" src="https://user-images.githubusercontent.com/19830500/243097837-3b451bd8-5802-4484-a1bf-ffb25b5b92e0.png">

大哥，你都没理清 Sonarr 和 Jackett 的基本逻辑，Audiences 是一个站点，如果你没有这个站点，怎么会去这个站点搜索呢？

**Comment by weigeloveu** [comment]
> > <img alt="截屏2023-06-03 21 37 50" width="834" src="https://user-images.githubusercontent.com/19830500/243097683-2c2fb272-6f9e-4935-9148-878857bcfe37.png"> 这个就是我手动添加的....(顺便问一下大佬用的哪个引擎,结果好多....) 我过滤这个Audiences咋就毛都没有.... <img alt="截屏2023-06-03 21 40 26" width="807" src="https://user-images.githubusercontent.com/19830500/243097837-3b451bd8-5802-4484-a1bf-ffb25b5b92e0.png">
> 
> 大哥，你都没理清 Sonarr 和 Jackett 的基本逻辑，Audiences 是一个站点，如果你没有这个站点，怎么会去这个站点搜索呢？

好的,大佬我回去补补课,等研究明白了,整篇小白友好向的教程,这些对我这个刚入门的小白还是太难了.

**Comment by weigeloveu** [comment]
> 我建议你先自行理清 Sonarr 的搜索逻辑，看你的日志截图，JProxy 是正常追加了主语言标题搜索的， 至于搜索到什么结果，跟关键字，分类，索引器都有关系，如果 Sonarr 跟 Jackett 直接搜索不一样，请自行对比搜索条件，大概率是你自己手动搜索的条件不一致（比如，根据你上述描述，你手动搜索的明显是 `我们之间没有的`，但是 JProxy 追加的是主语言标题 `即使你不和我做`，你添加的主语言标题不对该规则生效，因为主语言标题也只会取一个，你要就把 `即使你不和我做` 修改成其他语言，或者删除）

刚才测试了一下,删掉“即使你不和我做”之后,会默认追加繁体的我们之间没有的,最后才是我手动添加的标题.那这样是不是可以请求个新特性,追加标题优先级,如果最先优先级的查询结果不够按照优先级自动追加其他标题,直到结果找齐.(bt发布标题比较随心所欲,不同的组的也不太相同)

**Comment by LuckyPuppy514** [comment]
> > 我建议你先自行理清 Sonarr 的搜索逻辑，看你的日志截图，JProxy 是正常追加了主语言标题搜索的， 至于搜索到什么结果，跟关键字，分类，索引器都有关系，如果 Sonarr 跟 Jackett 直接搜索不一样，请自行对比搜索条件，大概率是你自己手动搜索的条件不一致（比如，根据你上述描述，你手动搜索的明显是 `我们之间没有的`，但是 JProxy 追加的是主语言标题 `即使你不和我做`，你添加的主语言标题不对该规则生效，因为主语言标题也只会取一个，你要就把 `即使你不和我做` 修改成其他语言，或者删除）
> 
> 刚才测试了一下,删掉“即使你不和我做”之后,会默认追加繁体的我们之间没有的,最后才是我手动添加的标题.那这样是不是可以请求个新特性,追加标题优先级,如果最先优先级的查询结果不够按照优先级自动追加其他标题,直到结果找齐.(bt发布标题比较随心所欲,不同的组的也不太相同)

1. 我都建议你修改了，删除不行，你就不能试试修改么，实在不行，你把另外一个也删除不行么（遇到问题，自己多尝试，只有自己多思考，多尝试，才玩得转）
2. 都能手动进行修正了，不会做逻辑修改的，追加太多标题，不但会对源站频繁请求，导致被屏蔽，而且只有极个别才会搜不到结果了，手动修正就行了

**Comment by weigeloveu** [comment]
> 

因为标题是自动出来的,不太确定修改后是否会对源数据产生影响(也没有找到相关的说明,目前来看都是大佬一个人在维护,相当辛苦,我摸索一下看看,抽空写点心得,算是完善一下wiki),保险起见就添加了一条,不过您说的频繁请求确实是个问题,增加追加请求间隔是否可行呢?毕竟要的就是自动化,总后台自己刷,间隔久一点也没什么.

**Comment by LuckyPuppy514** [comment]
1. 不知道你说的源数据是什么，JProxy 只是个过滤器，不会修改任何 Sonarr 的数据
2. 所有带标题搜索，都是人为手动搜索的，频繁不频繁都是人为的，就算加了间隔，你一直点搜索也没有什么意义，还得等半天，而且加太多只对极个别有意义的搜索标题，意义真的不大
3. 我建议你先熟悉 Sonarr 和 Jackett/Prowlarr，然后再熟悉 JProxy（至少把文档看了），有问题先看看已有 issue （你的标题+频繁搜索等等问题，都是已经有 issue，我也做了相应的回复）

另外，如果想要交流，请加Q群：921905633，而不是在 issue 里面讨论（一点都不方便，还影响其他人查找相关问题）
