### ISSUE TITLE
剧集规则同步功能报错

### ISSUE THREAD

**Issue by Para21** [LuckyPuppy514/jproxy#45]
![image](https://github.com/LuckyPuppy514/jproxy/assets/27716543/535591c9-ec7a-4ad7-b2b5-3eda88dadcd0)

**Comment by LuckyPuppy514** [comment]
看起来更像是你的网络有问题，请确保能访问下列地址，建议在服务器中执行

```bash
curl https://github.rn.lckp.top/LuckyPuppy514/jproxy/main/src/main/resources/rule/author.json
```

正常应如下图所示

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/b899b27e-cb3f-42e4-a312-885c28e87945)

**Comment by Para21** [comment]
好的，谢谢

**Comment by LuckyPuppy514** [comment]
如果实在搞不定，可以在这里下载，手动导入

[https://github.com/LuckyPuppy514/jproxy/tree/main/src/main/resources/rule](https://github.com/LuckyPuppy514/jproxy/tree/main/src/main/resources/rule)

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/d3023ee1-7e1a-4480-9397-705e31288caf)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/332aa025-2069-4bec-8bcc-f0b231e04ccb)
