### ISSUE TITLE
别名搜索的问题

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#46]
[**原始标题**

```text
Ousama ni Sasagu Kusuriyubi S01E07 2023 1080p KKTV WEB-DL x264
```

**问题描述**

这部剧集搜索的时候没有用别名来搜索，导致搜不到结果。动漫sonarr默认是用xem上动漫小组收集的的别名来搜索的，剧集看上去并不会用tvdb的别名，是不是只能自己proxy里加一下了

参考：
The Third Finger Offered To A King这部剧在TVDB是有罗马文别名Ousama ni Sasagu Kusuriyubi的：https://thetvdb.com/series/ousama-ni-sasagu-kusuriyubi

另外不知道jproxy里的动漫标题用的是哪家的数据，我试着搜了下Cardcaptor Sakura这部，一些别名好像跟xem上的不太一样

**Comment by LuckyPuppy514** [comment]
1. JProxy 对 Sonarr 搜索的优化，是利用 TMDB 标题进行优化的，我记得你是不开的，不开就没有任何优化，但是你也可以手动添加
2. 标题用的 TMDB 的数据，JProxy 只会追加 TMDB 标题进行搜索，其他别名搜索都是 Sonarr 本身的

我这里开启了 TMDB，是可以搜到结果的，你要是不想开，就只能自己手动添加对应的标题

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/6d322866-bd6f-409c-a976-87af00e52665)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/6fea8b6f-3c66-4b1f-9446-115dd766e7dc)

**Comment by PN62323424** [comment]
tmdb那个选项不是不好用，只是我懒得点开，不开tmdb的话新番一键就下了，开了的话好几个动漫站挂的更快，尤其是几十集那种

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/fc8815ea-ca8d-4265-a0f6-a707917a420a)

**Comment by LuckyPuppy514** [comment]
Sonarr 是从 TVDB 获取数据的，新番和新剧罗马音标题同步都比较慢，要等一段时间才会有

**Comment by PN62323424** [comment]
> Sonarr 是从 TVDB 获取数据的，新番和新剧罗马音标题同步都比较慢，要等一段时间才会有

明白了，感谢
