### ISSUE TITLE
幻樱未识别出简繁

### ISSUE THREAD

**Issue by maodun96** [LuckyPuppy514/jproxy#48]
**原始标题**

```text
【幻樱字幕组】【4月新番】【不知内情的转学生不管三七二十一缠了上来 Jijou wo Shiranai Tenkousei ga Guigui Kuru】【10】【BIG5_MP4】【1920X1080】
```

> 建议附上原始种子页面的链接
https://mikanani.me/Home/Episode/459db78d6e034aaf3861f881bb10f8972bf00c79
**问题描述**

未识别出简繁

**Comment by LuckyPuppy514** [comment]
已修复，请手动同步规则，或者等定时同步（每天凌晨自动同步一次）

**Comment by maodun96** [comment]
> 已修复，请手动同步规则，或者等定时同步（每天凌晨自动同步一次）

繁识别出来了，简还是没识别。
【幻樱字幕组】【4月新番】【什么情况都不知道的转校生一个劲地凑过来 Jijou wo Shiranai Tenkousei ga Guigui Kuru】【01】【GB_MP4】【1920X1080】
https://mikanani.me/Home/Episode/6f87b0f3dc9de8ff0785c481a42009848c2e4bb3

**Comment by LuckyPuppy514** [comment]
已修复
