### ISSUE TITLE
jproxy里的tmdb数据同步错误

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#49]
我有俩sonarr A和sonarr B(api key不同)，分别对应jproxy A和Jproxy B，Jproxy B的是用jproxy A的db文件覆盖安装的，然后配置好jproxy B以后，如果同步jproxy B的tmdb数据，会发现把sonarr A里的的同步过来。。。

**Comment by LuckyPuppy514** [comment]
同步是根据 JProxy 中的剧集标题同步的，你都把数据库复制过去了，当然会有 A 的数据，请自己手动删除

**Comment by LuckyPuppy514** [comment]
另外，提 issue 请按模板来

**Comment by PN62323424** [comment]
> 同步是根据 JProxy 中的剧集标题同步的，你都把数据库复制过去了，当然会有 A 的数据，请自己手动删除

我手动删过的，但点同步还是会同步回去，我提问前都是多次测试过才上来发issue的

**Comment by LuckyPuppy514** [comment]
按理来说不可能，但是请按模板说清楚自己的环境，两个就两个都说清楚，还有附上每个 JProxy 的配置截图，最好再附上剧集标题

**Comment by PN62323424** [comment]
**部署环境（windows / docker）**

群晖/docker

**问题描述**

jproxy配置是一样的，只不过sonarr地址及api key不一样，只要同步就会同步原数据库的标题出来

我知道听上去难以置信，但确实是这样，我多次测试过

**Comment by LuckyPuppy514** [comment]
请说清楚自己的环境，把 docker-compose 配置贴出来，并附上每个 JProxy 基础配置的截图，最好再附上剧集标题的截图

**Comment by LuckyPuppy514** [comment]
请像我这样提供以下信息

**jproxy 1**

```text
version: "3"
networks:
  network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.128.2.0/24

services:
  jproxy:
    image: luckypuppy514/jproxy:test
    container_name: jproxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 60215:8117
    volumes:
      - /docker/automatic-theater/config/jproxy/database:/app/database
    networks:
      network:
        ipv4_address: 172.128.2.15
```

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/db3fdf08-f678-4749-9833-ea87fce25971)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/38d12b80-c33f-46b5-8726-a995d1fa7cde)

**jproxy 2**

```text
version: "3"
networks:
  network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.128.3.0/24

services:
  jproxy-test:
    image: luckypuppy514/jproxy:test
    container_name: jproxy-test
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 60315:8117
    volumes:
      - /docker/devlop/config/jproxy/database:/app/database
    networks:
      network:
        ipv4_address: 172.128.3.15
```

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/6fb55b5b-a5e7-45f5-b518-58a856aa374c)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/054ef436-5ef0-42d4-a064-645f39e20317)

**Comment by LuckyPuppy514** [comment]
我自己亲测两个 Sonarr 和两个 JProxy 标题数据是不一样的

**Comment by PN62323424** [comment]
> 我自己亲测两个 Sonarr 和两个 JProxy 标题数据是不一样的

覆盖数据库的情况吗

**Comment by LuckyPuppy514** [comment]
大哥，我求求你，按我说的提供上述信息

**Comment by LuckyPuppy514** [comment]
覆盖也是一样，请你提供我说的信息

**Comment by PN62323424** [comment]
我上面提供的信息缺什么吗

**Comment by LuckyPuppy514** [comment]
剧集标题截图

**Comment by LuckyPuppy514** [comment]
另外，请提供下以下命令执行结果截图

```bash
ls -lai /volume1/docker/jproxy1/database
```

```bash
ls -lai /volume1/docker/jproxy2/database
```

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/967cff98-bf25-4ca7-8c92-473862bf3f70)

**Comment by PN62323424** [comment]
解决了，问题是出在复制数据库文件前必须删除“剧集标题”里的所有同步数据才能复制（我反复测试过确定是这个原因，权限我检查过没问题的），否则复制过去后删除没用，还是会同步之前的剧集标题。
