### ISSUE TITLE
修改搜索季度

### ISSUE THREAD

**Issue by tinlinz** [LuckyPuppy514/jproxy#5]
# 分类 - Type
1. 发布组 - ReleaseGroup
2. 动漫 - Anime
3. 电视剧 - TV Serial
4. 综艺 - TV Show
5. 其他 - Others

请输入你的选择 - please choose a number: 
2
规则类型：Anime
正则类型：搜索

我遇到的问题:
想要把`S04E01`替换成`第四季 01`，用下面的配置添加新规则后没有成功替换。

![截屏2022-08-02 15 14 58](https://user-images.githubusercontent.com/27729164/182316448-c79bc234-be75-491c-8c33-fbcb89a9522b.png)
![截屏2022-08-02 15 15 16](https://user-images.githubusercontent.com/27729164/182316665-983e443e-4576-478d-bbb4-593737c2aef9.png)

**Comment by LuckyPuppy514** [comment]
不建议这样更名，中文的话，sonarr不一定能识别
骨王第四季我这边可以，你可以参考我的索引器
![image](https://user-images.githubusercontent.com/53246532/182320051-f9f63743-67a6-433d-994b-e05d94d1aa40.png)

![image](https://user-images.githubusercontent.com/53246532/182320100-239e33f3-48c7-4509-ab4c-a52b03141d98.png)

**Comment by LuckyPuppy514** [comment]
还有个建议，把ANI字幕组的排除，sonarr下载完会根据文件名再判断一次，ani的文件名也是S04，导致不能识别，会导入到第一季
![image](https://user-images.githubusercontent.com/53246532/182320281-ffeae581-ddcb-4b9c-88bf-1a4f12fec3b5.png)

**Comment by LuckyPuppy514** [comment]
sonarr这个问题，有人提了ISSUE，不知道啥时候解决：https://github.com/Sonarr/Sonarr/issues/5073

**Comment by LuckyPuppy514** [comment]
我以为你说的结果QAQ
搜索的话，应该也不用替换了，按我设置的这几个索引器，能搜到不少结果

**Comment by tinlinz** [comment]
> 我以为你说的结果QAQ
> 搜索的话，应该也不用替换了，按我设置的这几个索引器，能搜到不少结果

好的，谢谢

**Comment by LuckyPuppy514** [comment]
> > 我以为你说的结果QAQ
> > 搜索的话，应该也不用替换了，按我设置的这几个索引器，能搜到不少结果
> 
> 好的，谢谢

Sonarr那个问题，我加入了 qBittorrent 代理解决，可以更新到最新版，并按文档重新设置一下：[配置文档 - v2.6.0](https://github.com/LuckyPuppy514/jproxy/blob/main/README.zh_CN.md#2-%E9%85%8D%E7%BD%AE)
