### ISSUE TITLE
Answer Me 1997净标题错误

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#52]
主标题：
Answer Me 1997

其中一个标题显示：
Reply 1997 E01 ì´ì¬ë 2012

其中一个净标题显示：
reply 1997 e01 ì´ì¬ë 2012

**Comment by LuckyPuppy514** [comment]
Sonarr 本身的问题

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/62871eef-ac16-4b21-acf9-11aca8cbeb0c)
