### ISSUE TITLE
请求加入设置代理功能

### ISSUE THREAD

**Issue by lostDeers** [LuckyPuppy514/jproxy#55]
**问题描述**

为服务（主要是tmdb的请求）提供一个设置代理的功能

**功能描述**

在界面中可设置代理地址

**Comment by LuckyPuppy514** [comment]
代理功能已经有了，请看 [README.md](https://github.com/LuckyPuppy514/jproxy#docker)，在 `JAVA_OPTS` 添加对应参数即可
如果只需代理 TMDB 接口，请自行在你的代理软件或插件中设置对应的规则即可
