### ISSUE TITLE
MIN_COUNT参数感觉没生效

### ISSUE THREAD

**Issue by WoodC2011** [LuckyPuppy514/jproxy#59]
**部署环境（windows / docker）**

docker

**问题描述**

我把MIN_COUNT改成了2000，即安装的时候添加了-e MIN_COUNT=2000，但搜索的时候只看到繁体主标题搜索，没看到简体及英文的主标题搜索，导致有一些结果搜不到

完整安装命令：
```
docker run --name jproxy \
--restart unless-stopped \
-e PUID=0 \
-e PGID=0 \
-e TZ=Asia/Shanghai \
-e MIN_COUNT=2000 \
-e JAVA_OPTS="-Xms512m -Xmx512m" \
-p 8117:8117 \
-v /volume1/docker/jproxy/database:/app/database \
-d luckypuppy514/jproxy:latest
```

**相关日志**

```
08-09 16:29:07 Info Torznab search in M-Team - TP for Fox Volant of the Snowy Mountain 2007 S01 => Found 0 releases [19785ms]
08-09 16:29:11 Info Torznab search in M-Team - TP for 雪山飛狐 S01 => Found 1 releases [4370ms]
08-09 16:29:15 Info Torznab search in M-Team - TP for 雪山飞狐 S01 => Found 3 releases [4096ms]
08-09 16:29:20 Info Torznab search in M-Team - TP for 雪山飛狐 => Found 3 releases [4375ms]
```

**Comment by LuckyPuppy514** [comment]
```text
Fox Volant of the Snowy Mountain 2007 S01
```

**Comment by LuckyPuppy514** [comment]
强调下，文档也有点问题，是追加 `主语言标题`，不会追加 `主标题`

**Comment by WoodC2011** [comment]
> 强调下，文档也有点问题，是追加 `主语言标题`，不会追加 `主标题`

哦，我还以为所有剧集英文标题都会追加

**Comment by LuckyPuppy514** [comment]
MIN_COUNT 的值不建议修改，除非你知道你在干嘛，不建议搞怎么大，导致所有搜索都一堆无意义结构，很容易被源站屏蔽

**Comment by LuckyPuppy514** [comment]
至于不是用的主语言标题，下个版本修复

**Comment by WoodC2011** [comment]
如果只是追加一个主语言标题，每季相当于多搜一次，这个影响不知道大不大

**Comment by LuckyPuppy514** [comment]
> 如果只是追加一个主语言标题，每季相当于多搜一次，这个影响不知道大不大

肯定有影响，影响大不大不是一句话就能说清楚，涉及的因素很多，包括但是不限于：

- 你手动或自动查询的频率，频率越高，影响肯定越大
- 你站点的数量，站点数量越多，查询就越慢
- 你站点的访问频率限制，频率上限越低，就越容易被源站屏蔽（简而言之就是黄色感叹号，暂时无法使用，参考馒头，很容易就挂掉）

此外，已经能够查询到大量数据的情况下，去除季数集数查询，基本上毫无意义，都是重复数据+大量无关数据

**Comment by LuckyPuppy514** [comment]
追加主语言标题问题，v3.4.0 已修复

```text
[Info] ReleaseSearchService: Searching indexer(s): [PTerClub] for Term: [Fox Volant of the Snowy Mountain 2007] for Season / Episode:[S01E01], Offset: 0, Limit: 100, Categories: [5000] 
[Info] ReleaseSearchService: Searching indexer(s): [PTerClub] for Term: [雪山飞狐] for Season / Episode:[S01E01], Offset: 0, Limit: 100, Categories: [5000] 
[Info] ReleaseSearchService: Searching indexer(s): [PTerClub] for Term: [雪山飛狐] for Season / Episode:[S01E01], Offset: 0, Limit: 100, Categories: [5000] 
[Info] ReleaseSearchService: Searching indexer(s): [PTerClub] for Term: [雪山飞狐] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000] 

```

**Comment by WoodC2011** [comment]
好的明白了，另外这部因为有好几个版本年份不一样但英文名差不多，有的标题格式化后会出错，这个例子你看下是否有必要修复，没必要的话我自己正则加个title标题

原标题：
The Flying Fox of Snowy Mountain 雪山飛狐 (1999) S01 1080p HDTV AAC H.264-OneHD 

格式化后标题：
Fox Volant of the Snowy Mountain (2007) S1 [Chinese][H.264][1080P][HDTV]

**Comment by LuckyPuppy514** [comment]
> 

这种暂时不修复了吧，意义不是很大，已完结的基本上都最好手动下载季包，自己打开种子详情页确认一下比较好

**Comment by WoodC2011** [comment]
TMDB同步标题是有频率限制吗，我连续下了七八部港剧，下到天龙八部、苗翠花的时候，发现这两部TMDB标题都同步不了了

**Comment by LuckyPuppy514** [comment]
> TMDB同步标题是有频率限制吗，我连续下了七八部港剧，下到天龙八部(1997)、苗翠花这两部的时候，发现jproxy里这两部的TMDB标题都同步不出来了，主要我站点多，手动挨个进去找很麻烦

有，如果同时订阅多个剧集，建议手动同步剧集标题和 TMDB 标题，然后再进行搜索（不要开启订阅后自动搜索，否则很可能有剧集因为频率限制需要等下次才能自动同步标题）

**Comment by WoodC2011** [comment]
TMDB上的老片子TVDB编码感觉错误的还是蛮多的，我随手下随手改，连天龙八部(1997)都是错的

**Comment by WoodC2011** [comment]
> MIN_COUNT 的值不建议修改，除非你知道你在干嘛，不建议搞怎么大，导致所有搜索都一堆无意义结构，很容易被源站屏蔽

MIN_COUNT这个参数能在UI里提供一个修改的入口吗，比如精确到剧集的MIN_COUNT。因为有的剧集比较经典，会有很多不同的重拍版本，像这种几乎都是超6个结果的但实际都是一些不能用的重拍版本，除非把MIN_COUNT改大才可以搜完整。

直接改2000结果确实比较乱，几乎都没法看了

**Comment by WoodC2011** [comment]
另外发现一个格式化错误标题，我自己改一下也可以，但按jproxy默认规则标题不应该格式化错误吧？（添加这部剧集都无法正确格式化title）

原始标题：
The.Legend.and.the.Hero.Complete.2006.WEB-DL.1080p.H264.AAC.Mandarin-OPS

格式化标题：
Match Title Fail S1 [1080P][WEBDL][-OPS]

原始链接：
https://ptsbao.club/details.php?id=7268&hit=1

**Comment by LuckyPuppy514** [comment]
有问题请分开提 issue，而不是一直讨论下去，这样没完没了了
而且你提的新问题完全是按自己的来，请务必按照 issue 模板提供必要信息

**Comment by LuckyPuppy514** [comment]
MIN_COUNT 我推荐默认值，你有需要可以自己调大，但是不建议一下子拉到 2000，我上面说了那么多，我不知道你到底看没看
这个值需要根据你自己的情况平衡，我给你的默认值就是我个人认为比较适合的值，你有需要只能你自己测试
