### ISSUE TITLE
导入时无法识别

### ISSUE THREAD

**Issue by jassysth** [LuckyPuppy514/jproxy#6]
**描述你的需求 - Describe Requirement**
请尽可能清楚的描述你的需求
虽然jproxy能识别更多资源了，但是如果下载下来的文件名不能够被sonarr识别，那么下载完后仍然需要手动导入，这个过程非常繁琐，有没有什么办法解决这个问题呢？

**Comment by LuckyPuppy514** [comment]
这是由于sonarr会在下载完再识别一次，是从qb那边取的种子名称
所以得加个qb代理，我正在弄，不出意外过几天能好

**Comment by jassysth** [comment]
好的，感谢大佬，辛苦了

**Comment by LuckyPuppy514** [comment]
不客气，有问题欢迎沟通，这个问题解决了我会再通知你

**Comment by LuckyPuppy514** [comment]
新版本已经发布，更新后按照文档重新设置一下：[配置文档 - v2.6.0](https://github.com/LuckyPuppy514/jproxy/blob/main/README.zh_CN.md#2-%E9%85%8D%E7%BD%AE)
