### ISSUE TITLE
添加这部剧集都无法正确格式化title

### ISSUE THREAD

**Issue by WoodC2011** [LuckyPuppy514/jproxy#60]
格式化错误标题，我自己改一下也可以，但按jproxy默认规则这个标题不应该格式化错误吧？（添加这部剧集都无法正确格式化title）

原始标题：
The.Legend.and.the.Hero.Complete.2006.WEB-DL.1080p.H264.AAC.Mandarin-OPS

添加剧集后并同步标题后的格式化标题测试：
Match Title Fail S1 [1080P][WEBDL][-OPS]

原始链接：
https://ptsbao.club/details.php?id=7268&hit=1

**Comment by LuckyPuppy514** [comment]
这个标题当前逻辑没问题，因为多了个 `Complete`，无法判断是标题就是有 `Complete` 还是代表 `已完结`，有需要可以自行添加标题规则修正

规则参考

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/d206636f-a74d-426d-b66f-fdbd8f8c25ba)


```text
[
    {
        "id": "A51A87DC150344E2A31F069A0B4E51B9",
        "token": "title",
        "priority": 900,
        "regex": ".*((?i)The(\\.| )Legend(\\.| )and(\\.| )the(\\.| )Hero(\\.| )Complete).*",
        "replacement": "The Legend and the Hero",
        "offset": 0,
        "example": "The.Legend.and.the.Hero.Complete.2006.WEB-DL.1080p.H264.AAC.Mandarin-OPS",
        "remark": "The Legend and the Hero",
        "author": "LuckyPuppy514",
        "validStatus": 1,
        "createTime": "2023-08-11 09:55:14",
        "updateTime": "2023-08-11 09:55:14"
    }
]
```

**Comment by WoodC2011** [comment]
我没太理解，你的意思是只要标题里有complete就会这样？还是说中间的那个```.```净标题没去掉的原因

**Comment by LuckyPuppy514** [comment]
简单的说 `The.Legend.and.the.Hero.Complete.2006.WEB-DL.1080p.H264.AAC.Mandarin-OPS` 会被识别为`The.Legend.and.the.Hero.Complete`

因为 `The.Legend.and.the.Hero` 和 `Complete` 之间没有任何明确的分隔符，且 `Complete` 不一定是什么特殊单词，很多剧集标题中就有 `Complete`，因此会被看成一个整体

**Comment by WoodC2011** [comment]
我把complete改成其他单词之类的，确实都不行，这个能修复吗

**Comment by WoodC2011** [comment]
另外TMDB缺少TVDB编码，添加后，jproxy无法自动同步的问题还是存在，我昨天加了部TMDB的TVDB编码，今天试过同步还是不行，必须sonarr删了原有剧集，再点同步才可以

**Comment by LuckyPuppy514** [comment]
> 我把complete改成其他单词之类的，确实都不行，这个能修复吗

当前逻辑就是这样，总不可能为了你这一个特例，把其他大部分弄成有问题吧
为什么一定要加单词？我不是给你规则参考了么，标题前后一定不能有英文单词，懂了么

**Comment by LuckyPuppy514** [comment]
> 另外TMDB缺少TVDB编码，添加后，jproxy无法自动同步的问题还是存在，我昨天加了部剧集TMDB的TVDB编码，今天试过tmdb标题的同步还是不行，必须sonarr删了原有剧集，再点同步才可以

你又来了，issue 不是论坛，请不要一个 issue 一直提出新问题，联系不大的问题请新开 issue
而且你这个又不是问题，你都知道 `TMDB缺少TVDB编码`，同步 TMDB 标题就是根据 TVDB编码同步的，都没有还怎么同步
而且即使你到 TMDB 添加了 TVDB 编号，TMDB 更新需要时间，JProxy 同步标题也需要时间，如果你想要自动同步就耐心等待就行了，着急就自己手动同步

**Comment by WoodC2011** [comment]
1.我没让你把所有人的都改错，而且complete并不是特例，我意思只是问你这个问题能否解决
2.我说过TVDB编码昨天没有，但昨天我加上以后已经有了

你自己看不懂我说的，反过来说我不懂？

**Comment by LuckyPuppy514** [comment]
> 1.我没让你把所有人的都改错，而且complete并不是特例，我意思只是问你这个问题能否解决 2.我说过TVDB编码昨天没有，但昨天我加上以后已经有了
> 
> 你自己看不懂我说的，反过来说我不懂？
> 
> 看我原文怎么写的，我给你标记出来省的你看不懂
> 
> `我昨天加了部剧集TMDB的TVDB编码，今天试过tmdb标题的同步还是不行`
> 
> 怎么到你这能理解成`你都知道 TMDB缺少TVDB编码，同步 TMDB 标题就是根据 TVDB编码同步的，都没有还怎么同步`

1. 我上面已经给了答复了，无法判断 `Complete` 是否是标题，还是特殊意义的单词，有需要可以自己加规则，而且我已经给了规则参考，亲测没有问题，你还要我怎么改

2. 能不能认真看回复，TMDB 不是你修改了就马上有的，需要时间懂吗，而且我完全可以不回复你的这个问题，昨天你的另外一个 issue 已经提醒过了，每个问题分开提

3. 我稍微说错了一点，你就这种态度的话，我建议你另寻高明，我想先请问你自己有认真看我的回复么，如果有，你为什么还同一个 issue 一直追加问题 #59

**Comment by WoodC2011** [comment]
1.我有逼你改，我不也只是客气问你能否解决？还要我怎么说？我有逼你解决？
2.你能不能认真看回复，TMDB改是昨天改的，今天在我删除sonarr以后，就马上可以同步了

**Comment by LuckyPuppy514** [comment]
> 1.我有逼你改，我不也只是客气问你能否解决？还要我怎么说？我有逼你解决？ 2.你能不能认真看回复，TMDB改是昨天改的，今天在我删除sonarr以后，就马上可以同步了

1. 我有说你逼我改了么，我上面说了有需要可以自己加规则，还给了参考例子，你自己第一非要问能不能改，第二非要自己写规则说不行，我能怎么办，还一直问有意义吗
2. 昨天改的就马上能同步了么，你有什么证据在你删除之前 TMDB 的数据就更新了呢，而且 TMDB 标题只要同步一个就不会再同步了，你是否检查了原来有没有同步到一个标题呢，还有各种各样的情况，请问你提问之前至少按照模板提供必要信息了么，反而是按照昨天的态度一直同一个 issue 追加问题，不按模板来，我就按你的随意提，随意回复，不行吗？

**Comment by WoodC2011** [comment]
1.我问能不能改都不能问了？不能问那你还开issue做什么，关了算了啊
2.我火大是因为你这态度，什么叫```总不可能为了你这一个特例，把其他大部分弄成有问题吧```，我有逼你做什么？
3.你又来了，我说了sonarr里删除剧集重新添加以后，就马上可以同步了，不删就是同步不了，你以为每个用户都是菜鸡？我正则全部自己搞定的，这点逻辑我搞不清楚？
4.我是没按模板提供信息啊，我按你自己的逻辑回复你```我稍微说错了一点，你就这种态度的话，我建议你不要开issue```

**Comment by LuckyPuppy514** [comment]
> 1.我问能不能改都不能问了？不能问那你还开issue做什么，关了算了啊 2.我火大是因为你这态度，什么叫`总不可能为了你这一个特例，把其他大部分弄成有问题吧`，我有逼你做什么？ 3.你又来了，我说了sonarr里删除剧集重新添加以后，就马上可以同步了，不删就是同步不了，你以为每个用户都是菜鸡？我正则全部自己搞定的，这点逻辑我搞不清楚？ 4.我是没按模板提供信息啊，我按你自己的逻辑回复你这一点`我稍微说错了一点，你就这种态度的话，我建议你不要允许用户开issue，发现一个issue删一个，也绝对不要按用户提交的issue来修bug`

1. 我上面已经给了我个人能提供的最好的答案，你非要问能不能改，好，我现在明确告诉你不会改，因为我个人能力有限，无法通过其他信息判断 `Complete` 或其他任意单词，在没有明确分隔符的情况下，与其他英文单词构成的短语，是不是一个整体

当前逻辑会强制判断成一个整体，避免`AAA BBB` 被识别为 `AAA`
如果按你的要求改，就会导致上述问题，如果按条件改，直接通过规则即可实现，上面已经给了规则范例了，如果改代码，就可能因为这个个例，衍生更多不可控制的问题

2. 你火大，我就没有火，我昨天提醒了分开提 issue，我上面认认真真给了答复，解决办法，请问你尝试了么，为什么还要自己写规则，还说不行，你不能理解我的回复，能认真多看两遍吗，你可以不理解我的答复，我就一定要理解你随意在同一个 issue 追加的其他问题？什么道理？

3.  我说那些，是让你提问要按模板提供必要信息，否则无头苍蝇找问题没有意义，一堆情况怎么解决问题？
另外，我哪里说每个用户是菜鸡了？？？你不要你以为你以为，你自己不爽就可以张口就来？

4. 没按模板来，我完全可以不回复，回复了你又觉得人家针对你，态度不好，请问你态度好到哪里去了

5.  从头到尾除了你的口头说明，有任何截图，日志证明吗？还有你到现在都不理解，我说的就是一种情况，你连问题模板的信息都不提供，你知道能有多少情况吗？
6.
