### ISSUE TITLE
未匹配到标题 

### ISSUE THREAD

**Issue by maodun96** [LuckyPuppy514/jproxy#61]
**原始标题**

```text
【高清剧集网发布 www.DDHDTV.com】乐队的夏天 第三季[第00-01集][上][下][国语配音+中文字幕].The.Big.Band.S03.2023.2160p.WEB-DL.DDP2.0.H265-Huawei
```

> 建议附上原始种子页面的链接
https://btdig.com/77e2913fa96a5202f51b9433966afca98d2e7fe7/%E4%B9%90%E9%98%9F%E7%9A%84%E5%A4%8F%E5%A4%A9
**问题描述**

简要描述有什么问题
在预览中未匹配到标题
![image](https://github.com/LuckyPuppy514/jproxy/assets/43996175/bd26983c-2709-4148-af76-33f4e51df97f)

**Comment by LuckyPuppy514** [comment]
你得先在 Sonarr 订阅对应的剧，并且等 JProxy 同步了对应的标题（也可以手动同步一下），才会匹配标题

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/8ee39557-454e-4451-ab12-be732f155554)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/5d39a7f3-cdb8-4edf-bc09-aacc26585c8c)

**Comment by maodun96** [comment]
@LuckyPuppy514 忘了这一茬 不好意思
