### ISSUE TITLE
格式化的剧集标题很多不含压制组

### ISSUE THREAD

**Issue by kristianvmd** [LuckyPuppy514/jproxy#64]
部署环境：

docker

问题描述：
1.剧集范例和格式化标题结果不一致
2.格式化的剧集标题不含压制组

复现过程：

1.sonarr里使用PT站观众搜索超能异族
2.原标题——Moving S01E01-E07 2023 2160p DSNP WEB-DL H265 HDR DDP5.1 Atmos-ADWeb
3.剧集范例里测试结果——Moving (2023) S1E1-E7 [H265][2160P][HDR][WEBDL][-ADWeb]
4.实际格式化标题——Moving (2023) S1E1-E7 [Chinese][H265][2160P][HDR][WEBDL]——剧集范例里并没有[Chinese]
5.链接：https://audiences.me/details.php?id=184136&hit=1

其他站点也有这种情况：

站点：小蚂蚁
原标题：Moving 2023 S01 E01-E09 2160p HULU WEB-DL H.265 10bit DDP5.1-PTerWEB
剧集范例里测试结果：Moving (2023) S1E1-E9 [H.265][2160P][WEBDL][10bit][-PTerWEB]
实际格式化标题：Moving (2023) S1E1-E9 [H.265][2160P][WEBDL][10bit]
链接：https://hdmayi.com/details.php?id=23618&hit=1

站点：馒头
原标题：Moving S01E01-E07 2023 2160p DSNP WEB-DL H.265 DV DDP5.1 Atmos-ADWeb
剧集范例里测试结果：Moving (2023) S1E1-E7 [H.265][2160P][WEBDL][-ADWeb]
实际格式化标题：Moving (2023) S1E1-E7 [H.265][2160P][WEBDL]
链接：https://kp.m-team.cc/details.php?id=700308&hit=1

**Comment by LuckyPuppy514** [comment]
```text
Moving S01E01-E07 2023 2160p DSNP WEB-DL H265 HDR DDP5.1 Atmos-ADWeb
```
馒头和观众你说的这个标题是有问题的，默认不可能匹配成功的，因为少了 `2023`，如果你的可以，证明你自己修改过规则或标题

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/12cf07f8-0263-457c-9075-bad1f1a73930)

小蚂蚁我没有，但是猫站是没问题的

![20230903200349](https://github.com/LuckyPuppy514/jproxy/assets/53246532/1378f6a3-0895-49e4-a8d1-637299157012)

综上，更有可能是你修改了什么规则导致冲突了，或者你修改了索引器格式

![20230903200555](https://github.com/LuckyPuppy514/jproxy/assets/53246532/7b0dc5c0-daec-40b1-9167-a71fa4af5026)

**Comment by kristianvmd** [comment]
moving这部我确实加了规则，我补了条你group规则里的这条.*(-\|@)([a-zA-Z]+)($\| / .*)  然后压制组就没问题了，但我即便没加.*(-\|@)([a-zA-Z]+)($\| / .*)这条，剧集范例里也是没问题的，只不过搜索结果里不对，剧集范例里的测试和实际格式化结果为什么不一样呢

**Comment by LuckyPuppy514** [comment]
可能是你加了规则没有清理缓存，导致 Sonarr 查询的结果是缓存（范例的结果是不会缓存的），修改了规则必须清理所有缓存

PS：请认真看文档，文档中有建议单个正则尽量简单化，可采取多个规则的方式实现同样的效果，特别是你对正则不熟悉的情况
另外，贴规则不要只贴正则，请截图完整的规则，或者导出后把文件内容以代码形式贴上来（其他条件一样会影响结果，只有正则无法复现问题）
