### ISSUE TITLE
副标题的格式化逻辑能否调整下

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#66]
我不太清楚目前的副标题格式化逻辑，所以提的建议可能不太准确

副标题里的季信息很多都是汉字不方便写正则，比如第一到第七季，全三季之类的，如果改成只获取里面的标题，其余的信息不要获取这样是否会好一些

像这个链接: https://kp.m-team.cc/details.php?id=276478&hit=1 的副标题是```冰与火之歌第一到第七季原盘Remux合集（含全套衣柜特效字幕及一个方正字体）```

jproxy从里面获取了"第一到第七季"，使得最终格式化标题是Game of Thrones S7 [1080P][Bluray]，如果想格式化"第一到第七季"这种类型标题的话就很难没法用一个正则解决

另一个链接: https://kp.m-team.cc/details.php?id=638985&hit=1 的副标题是```权力的游戏第一季-第八季+衣柜字幕组特效字幕By云中漫步```

jproxy的格式化结果是[Game of Thrones S8 [H.264][1080P][10bit][-权力的游戏第一季-第八季+衣柜字幕组]，这个结果更为混乱一些

————总之副标题里的信息太混乱了，能匹配上的规则都没几条，我觉得副标题只适合用来获取并格式化标题，其余的信息还是从主标题里获取效果更好————

**Comment by LuckyPuppy514** [comment]
少数格式比较混乱的，有需要建议自行添加规则处理，暂时不做改动了

**Comment by PN62323424** [comment]
副标题其实不是少数格式混乱，冷门点的剧集只要使用中文搜索，就会搜出很多奇怪的格式化结果，想完全用规则匹配几乎是不可能的事（原因副标题没有规律可寻），相当于之前的规则用在副标题上的话大部分都失效了。

热门剧集因为搜出来的结果基本都是大于6的，所以感觉不出来副标题带来的影响，实际影响是很大的

**Comment by LuckyPuppy514** [comment]
我没遇到过相关的例子，你举例的也没啥大问题，而且 Sonarr 应该是不支持多季同时导入的，这种都建议手动抓取导入

**Comment by LuckyPuppy514** [comment]
很多PT站把集数，语言等信息放在副标题，必须带上副标题的信息

**Comment by PN62323424** [comment]
嗯，确实有的信息就副标题有，还是保持现状吧

我去补点规则算了，当前是副标题里的哪些内容添加到格式化后的标题，我看格式化后的结果好像都是用的主标题的，只是部分用的副标题

**Comment by PN62323424** [comment]
我如何用jproxy测试格式化结果？

Soldiers Sortie S01 2006 2160p / 士兵突击 全30集 主演: 王宝强

这样直接丢jproxy里？

**Comment by LuckyPuppy514** [comment]
可以，有问题记得先清空所有缓存
