### ISSUE TITLE
請問這個項目能跟Xarr-Rss同時並用嗎?

### ISSUE THREAD

**Issue by xiNeRoar** [LuckyPuppy514/jproxy#67]
想知道能不能同時使用兩套服務還是說會互相干擾?

**Comment by maodun96** [comment]
> 想知道能不能同時使用兩套服務還是說會互相干擾?

这个开发者不一定在用，所以我来回答一下。

互不影响的，因为对于sonarr来说只是两个不同的索引。他们的源可能是同一个，例如dmhy，但是经过各自的代理都需要在sonarr产生一个独特的索引。至于把两者嵌套起来使用，应该不可行。

**Comment by xiNeRoar** [comment]
> > 想知道能不能同時使用兩套服務還是說會互相干擾?
> 
> 这个开发者不一定在用，所以我来回答一下。
> 
> 互不影响的，因为对于sonarr来说只是两个不同的索引。他们的源可能是同一个，例如dmhy，但是经过各自的代理都需要在sonarr产生一个独特的索引。至于把两者嵌套起来使用，应该不可行。

謝謝你，請問你嵌套是什麼意思? 如果我沒理解錯你的意思應該是兩套軟件可以並行同時一起用是嗎?

**Comment by maodun96** [comment]
> > > 想知道能不能同時使用兩套服務還是說會互相干擾?
> > 
> > 
> > 这个开发者不一定在用，所以我来回答一下。
> > 互不影响的，因为对于sonarr来说只是两个不同的索引。他们的源可能是同一个，例如dmhy，但是经过各自的代理都需要在sonarr产生一个独特的索引。至于把两者嵌套起来使用，应该不可行。
> 
> 謝謝你，請問你嵌套是什麼意思? 如果我沒理解錯你的意思應該是兩套軟件可以並行同時一起用是嗎?

是的 可以并行存在。我说的嵌套是只两者其中一个作为另外一个的数据源。这种操作应该是不行的。

**Comment by LuckyPuppy514** [comment]
没有一起使用过，也不建议这样做

**Comment by xiNeRoar** [comment]
> 没有一起使用过，也不建议这样做

謝謝你的回覆，會想這樣使用是因為即使用了jproxy還是沒法讓sonarr優先抓取字幕組發佈的中文動畫，xarr-rss內建有這個功能但又沒法抓取過往的舊動畫只能下載當前最新發佈一話，所以才想一起用看能不能解決我的問題

**Comment by maodun96** [comment]
> > 没有一起使用过，也不建议这样做
> 
> 謝謝你的回覆，會想這樣使用是因為即使用了jproxy還是沒法讓sonarr優先抓取字幕組發佈的中文動畫，xarr-rss內建有這個功能但又沒法抓取過往的舊動畫只能下載當前最新發佈一話，所以才想一起用看能不能解決我的問題

你想要的是先下台版b站版本、后期自动换源对吗？这个建议你补习一下sonarr的设定，v3我太久没用了，应该可以做到。v4版本的自定义命名格式是可以实现类似功能的。

**Comment by LuckyPuppy514** [comment]
> > > 没有一起使用过，也不建议这样做
> > 
> > 
> > 謝謝你的回覆，會想這樣使用是因為即使用了jproxy還是沒法讓sonarr優先抓取字幕組發佈的中文動畫，xarr-rss內建有這個功能但又沒法抓取過往的舊動畫只能下載當前最新發佈一話，所以才想一起用看能不能解決我的問題
> 
> 你想要的是先下台版b站版本、后期自动换源对吗？这个建议你补习一下sonarr的设定，v3我太久没用了，应该可以做到。v4版本的自定义命名格式是可以实现类似功能的。

sonarr v3 和 v4 都可以实现该功能，自定义分数即可

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/481489ac-7036-4248-b114-b40a21d5715b)

**Comment by xiNeRoar** [comment]
> > > > 没有一起使用过，也不建议这样做
> > > 
> > > 
> > > 謝謝你的回覆，會想這樣使用是因為即使用了jproxy還是沒法讓sonarr優先抓取字幕組發佈的中文動畫，xarr-rss內建有這個功能但又沒法抓取過往的舊動畫只能下載當前最新發佈一話，所以才想一起用看能不能解決我的問題
> > 
> > 
> > 你想要的是先下台版b站版本、后期自动换源对吗？这个建议你补习一下sonarr的设定，v3我太久没用了，应该可以做到。v4版本的自定义命名格式是可以实现类似功能的。
> 
> sonarr v3 和 v4 都可以实现该功能，自定义分数即可
> 
> ![image](https://user-images.githubusercontent.com/53246532/268498234-481489ac-7036-4248-b114-b40a21d5715b.png)

非常感謝，我自己再研究一下，先關掉這條issue

**Comment by mapleshadow** [comment]
> > > > 没有一起使用过，也不建议这样做
> > > 
> > > 
> > > 謝謝你的回覆，會想這樣使用是因為即使用了jproxy還是沒法讓sonarr優先抓取字幕組發佈的中文動畫，xarr-rss內建有這個功能但又沒法抓取過往的舊動畫只能下載當前最新發佈一話，所以才想一起用看能不能解決我的問題
> > 
> > 
> > 你想要的是先下台版b站版本、后期自动换源对吗？这个建议你补习一下sonarr的设定，v3我太久没用了，应该可以做到。v4版本的自定义命名格式是可以实现类似功能的。
> 
> sonarr v3 和 v4 都可以实现该功能，自定义分数即可
> 
> ![image](https://private-user-images.githubusercontent.com/53246532/268498234-481489ac-7036-4248-b114-b40a21d5715b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzE3NjksIm5iZiI6MTczNDQzMTQ2OSwicGF0aCI6Ii81MzI0NjUzMi8yNjg0OTgyMzQtNDgxNDg5YWMtNzAzNi00MjQ4LWIxMTQtYjQwYTIxZDU3MTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEwMzEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYmNlYTkyNWM4YzY4MzVjMWYxOGMxZjMwNDAzOTczOTAxMDhjNmIzZTJjYzE3Y2YzNDlhMzc1YjJmMjU2NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hkg4yPiOo40yrh8oeaUzZ5hY8s6kJrNvCpvcU8bcANs)

v4目前还不支持多语言吧？没找到哪里可以设置中文
