### ISSUE TITLE
2160P识别为1080P

### ISSUE THREAD

**Issue by maodun96** [LuckyPuppy514/jproxy#69]
**原始标题**

【高清剧集网发布 www.DDHDTV.com】风起陇西[全24集][国语配音+中文字幕].The.Wind.Blows.From.Longxi.2022.S01.2160p.WEB-DL.H265.DDP2.0-Huawei

> 建议附上原始种子页面的链接
https://idope.se/torrent/Wind%20Blows%20From%20Longxi%20S01/ca3ca3805e89bc7f6d1bee61c054710c80cd229c/

**问题描述**

2160P识别为1080P
The Wind Blows From Longxi S1 [Chinese][1080P][WEBDL][-高清剧集网发布 www.DDHDTV.com]

**Comment by LuckyPuppy514** [comment]
已修复，手动同步规则，或者等待每天晚上定时自动同步即可
