### ISSUE TITLE
Sonarr裡搜尋不到Jproxy的indexer server

### ISSUE THREAD

**Issue by xiNeRoar** [LuckyPuppy514/jproxy#70]
**部署环境（windows / docker）**

docker

**问题描述**

按照設置教學裡面設定好之後，在Sonarr裡無法搜尋到jproxy的indexer server

**相关日志**
Jproxy日志
![image](https://github.com/LuckyPuppy514/jproxy/assets/66216186/c59f7093-6c6c-4900-92fb-6c7538c12e9e)
Sonarr日志
![image](https://github.com/LuckyPuppy514/jproxy/assets/66216186/ba0b4942-d792-4e2a-a886-e457be6e74ad)

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/c65b2574-43b2-4959-ab13-6514e8e4722b)

不是 JProxy 的问题，是你被源站屏蔽了，要等到今晚 12:29:15 后才可以访问

**Comment by xiNeRoar** [comment]
謝謝你的耐心解答...對於完全不會代碼的小白來說要找出下載不了劇集的原因還真困難....
