### ISSUE TITLE
批量添加规则的问题

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#71]
写了一些规则，挨个手动加有点麻烦。我看了下.json文件，能直接改这个吗

{"id":"517B59DE054244BAABE1B5D693D0457F","token":"title","priority":500,"regex":".*(?i)(Three Kingdoms|三国|Three.Kingdoms).*(1997).*","replacement":"The Romance of the Three Kingdoms: Edited Edition","offset":0,"example":"123","remark":"三国演义 (精编版)","author":"tony"}

其余的应该没问题，但id这个怎么填呢？

**Comment by LuckyPuppy514** [comment]
百度或谷歌 UUID在线生成，去掉`-`，大写即可
