### ISSUE TITLE
标题里中文冒号，中文括号的问题

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#74]
**问题描述**

TMDB上很多剧集的标题里含有：（）这样的中文标点，比如海军罪案调查处：洛杉矶、D.P：逃兵追缉令，TMDB的中文标题里的中文标点前后都没空格的，导致jproxy把搜索词格式化成海军罪案调查处洛杉矶，D P逃兵追缉令，也就是没空格，这样会导致很多结果搜不出来，而且像剧集的话，TMDB的中文标题里带中文标点是很常见的，动漫的话就更多了。

我随手找出的TMDB上带中文标点的几个链接：
https://www.themoviedb.org/tv/17610-ncis-los-angeles/edit?active_nav_item=primary_facts
https://www.themoviedb.org/tv/110534-d-p/edit?active_nav_item=primary_facts
https://www.themoviedb.org/tv/2734-law-order-special-victims-unit
https://www.themoviedb.org/tv/70998

馒头搜索测试方法：
比如用D P逃兵追缉令在馒头只能搜出一个结果，而用D P 逃兵追缉令就可以把所有结果都搜出来

**功能描述**

有没办法规避下中文标点造成的无空格的问题，比如遇到中文标点，后面有内容的话，就自动加个空格？

当然英文符号我觉得带个空格能搜出的结果也更多，类似[毒枭巴勃罗·埃斯科巴](https://www.themoviedb.org/tv/43348-pablo-escobar-el-patron-del-mal)这种，格式化的中文标题也会变成“毒枭巴勃罗埃斯科巴”这种长句子，会造成搜不出结果来

**Comment by LuckyPuppy514** [comment]
重复的问题：[#72](https://github.com/LuckyPuppy514/jproxy/issues/72)
再次解释一下，JProxy 搜索不会对标题做任何修改，不会去除任何字符，但是 Sonarr 会
如果是 Sonarr 已经去除的，没法复原，如果是 JProxy 中同步的 TMDB 标题，有需要你完全可以自己修改

**Comment by LuckyPuppy514** [comment]
这个的话，后续再说，因为我还没了解过 Sonarr / Jackett 去除中文标点符号的规则，说不定有些去除了反而有问题
而且当前暂时就你一个人反馈这个问题，所以还是建议先手动修改

**Comment by PN62323424** [comment]
确实是Sonarr / Jackett的原因，jproxy格式化的是对的带空格的，但jackett里日志都是没空格的
