### ISSUE TITLE
遇到蛮特殊的无法自动导入的问题

### ISSUE THREAD

**Issue by kristianvmd** [LuckyPuppy514/jproxy#75]
**部署环境（windows / docker）**

docker

**问题描述**

这个链接的下载好的文件无法自动导入，文件标题是《大小姐和看門犬》#2 (簡繁日內封字幕   日語原聲)【Ani-One Asia】.mp4
https://miobt.com/show-fc89ff3824fbb7d79b2f23864518aa7765c2f097.html

而这个链接的下载好的文件可以自动导入，文件标题是[ANi] 大小姐和看門犬 - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4
https://www.comicat.org/show-ed104a57be2a3559c2cbc154f5d34cf08e5a4341.html

不知道是不是sonarr下载好的文件进行了二次识别导致的，我下动漫的时候经常遇到没法自动导入的，以前没留意今天仔细看了下，感觉是这个原因。

我检查了下载文件夹，似乎jproxy只格式化了文件夹的名字，动漫一般都是单独的下载文件并没有文件夹，并没有格式化标题，是不是没格式化单个文件标题造成了sonarr无法导入。

**Comment by LuckyPuppy514** [comment]
可以看下 [wiki](https://github.com/LuckyPuppy514/jproxy/blob/main/wiki.md#qbittorrent)

- Sonarr 导入的时候会根据种子名和文件名再次识别
- qBittorrent 支持重命名文件，Transmission 只有重命名种子接口，没有重命名文件接口，所以不行

**Comment by kristianvmd** [comment]
我用的就是qbittorrent，也完全按照wiki填的，文件夹的重命名我在download里能看到确实重命名了，但这个链接的下载好的文件download里我没看到重命名，也无法自动导入，文件原标题是《大小姐和看門犬》#2 (簡繁日內封字幕 日語原聲)【Ani-One Asia】.mp4，链接是
https://miobt.com/show-fc89ff3824fbb7d79b2f23864518aa7765c2f097.html

能麻烦您那测试下这部的第二集吗，其余的也蛮多这种情况的，我看文件在donwload里还是原来的名字，文件夹都成功重命名了。

**Comment by kristianvmd** [comment]
我用的qbittorrent版本是qBittorrent v4.5.2，容器安装的。

**Comment by kristianvmd** [comment]
我好像动漫用了aria2来下载的。。。。不好意思，aria2能添加下支持吗。。。qbittorrent我只用来保种及刷流的

**Comment by kristianvmd** [comment]
PT的话站点不都要求关闭DHT的，我担心影响速度就没用QB来下BT

**Comment by LuckyPuppy514** [comment]
> PT的话站点不都要求关闭DHT的，我担心影响速度就没用QB来下BT

不影响的，PT 种子会自动关闭，BT 种子会自动开启
aria2 暂时没时间支持，建议使用 qBittorrent

PS：一般 qBittorrent 下载，Transmission 辅种吧 🤣

**Comment by kristianvmd** [comment]
期待能支持aria2，qBittorrent我感觉性能还行，就没转移到Transmission。
