### ISSUE TITLE
间谍过家家无法追番

### ISSUE THREAD

**Issue by kristianvmd** [LuckyPuppy514/jproxy#77]
**部署环境（windows / docker）**

docker

**问题描述**

第二季第一集开始没法追了，之前都没问题，但第二季开始发布组标题里都开始用26集对应第二季第一集，完全乱掉了，而且还带了个season 2，搜索词也不知道怎么改....请问这种情况如何处理？另外搜素的时候并不会搜E26而是E1，我不太明白，明明TVDB上是S02E01。

[[Skymoon-Raws] 间谍过家家 第2期 / SPY×FAMILY Season 2 - 26 [ViuTV][WEB-DL][1080p][AVC AAC][繁体外挂]

https://mikanani.me/Home/Episode/234c31e6a73fb73156dce47280848e7328a10dd4

**Comment by LuckyPuppy514** [comment]
加个规则修正即可，晚点有空我加下

**Comment by LuckyPuppy514** [comment]
[已提交，手动同步下规则，清空所有缓存后再试试](https://github.com/LuckyPuppy514/jproxy/commit/f9b04813a6cbc93e76342d8121bc1829685ed45e)

**Comment by kristianvmd** [comment]
你那能搜出来吗，搜索词没变还是E01，搜不出来第26集啊，[Skymoon-Raws] 间谍过家家 第2期 / SPY×FAMILY Season 2 - 26 [ViuTV][WEB-DL][1080p][AVC AAC][繁体外挂]

**Comment by LuckyPuppy514** [comment]
搜索你可以尝试调整参数 `MIN_COUNT`，具体说明看文档，不建议太大，比每个站点搜索到的结果数量稍微大一点就行了

```text
version: '3.0'
services:
   jproxy:
      image: luckypuppy514/jproxy:latest
      container_name: jproxy
      restart: unless-stopped
      environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx512m
      - MIN_COUNT=调大这个值，默认是6
      ports:
      - 8117:8117
      volumes:
      - /docker/jproxy/database:/app/database
```

**Comment by kristianvmd** [comment]
谢谢，我改成500了，但没去掉集和季啊，都是带个01的，不过我试了下其他动漫确实去掉了只是这部没有。

[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [SPYxFAMILY 01], Offset: 0, Limit: 100, Categories: [5000, 5050, 5070, 124339]
[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [SPY FAMILY 01], Offset: 0, Limit: 100, Categories: [5000, 5050, 5070, 124339]
[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [Spy x Family Part 2 01], Offset: 0, Limit: 100, Categories: [5000, 5050, 5070, 124339]
[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [SPY x FAMILY S2 01], Offset: 0, Limit: 100, Categories: [5000, 5050, 5070, 124339]
[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [SPYxFAMILY S2 01], Offset: 0, Limit: 100, Categories: [5000, 5050, 5070, 124339]
[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [SPY FAMILY S2 01], Offset: 0, Limit: 100, Categories: [5000, 5050, 5070, 124339]
[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [SPY x FAMILY 01], Offset: 0, Limit: 100, Categories: [5000, 5050, 5070, 124339]
[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [间谍过家家 01], Offset: 0, Limit: 59, Categories: [5000, 5050, 5070, 124339]
[Info] ReleaseSearchService: Searching indexer(s): [MioBT] for Term: [SPY×FAMILY 間諜家家酒 01], Offset: 0, Limit: 10, Categories: [5000, 5050, 5070, 124339]

**Comment by kristianvmd** [comment]
这是第二季第一集全部的搜索日志。

**Comment by LuckyPuppy514** [comment]
500 可能不够，是几个标题累计的数量，我这边是有 PT 站，有比较规范的 S2 01 所以没问题
