### ISSUE TITLE
仅以S1E1这样来命名文件，会导致所有的剧集升级失败

### ISSUE THREAD

**Issue by WoodC2011** [LuckyPuppy514/jproxy#79]
**部署环境（windows / docker）**

docker

**问题描述**

仅以S1E1这样来命名文件，会导致所有的剧集自动升级失败（第一次下载不影响），我在sonarr官方那里得到的反馈如下

https://github.com/Sonarr/Sonarr/issues/6095

以前sonarr导入的时候可能不会重新计算质量得分，最近重新计算了

**Comment by LuckyPuppy514** [comment]
你可以切到 test 版本试试，文件重命名我追加了其他信息，但是分数没有变化
我以前好像也这样做过，既没效果，可能还有副作用，所以放弃了

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/0f1b926c-0afd-4b95-a341-5643d12589b7)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/0a49e971-1548-4707-98bd-64c672dfce5a)

**Comment by WoodC2011** [comment]
我没太看明白你说的

但我刚才试了下test版，文件夹里的mkv文件命名现在正确了，也可以正常升级了

**Comment by LuckyPuppy514** [comment]
> 我没太看明白你说的
> 
> 但我刚才试了下test版，文件夹里的mkv文件命名现在正确了，也可以正常升级了

我的意思是，我这边改了，分数还是一样

**Comment by WoodC2011** [comment]
我这个图片里显示的分数是未导入的文件显示的分数
![image](https://github.com/LuckyPuppy514/jproxy/assets/57359623/97655d2d-78a4-4a3c-b892-8e11d5a4bb7f)

不过奇怪的是新的test版，即便手动下了低分的也可以自动导入，我不太确定是sonarr还是jproxy的原因，但至少现在可以自动升级了

**Comment by WoodC2011** [comment]
你是不是说的是你那边即便升级到test，重命名的文件名还是S1E1这种，mkv文件的标题里并没有添加自定义格式？

**Comment by WoodC2011** [comment]
我明白你意思了，稍等我这对比试一下

**Comment by WoodC2011** [comment]
我这试了下，是否用test版，历史记录里分数确实是一样的，因为历史记录里记录的并不是S1E1而是jproxy格式化过的标题，自动导入的时候分数不一样，因为sonarr读到S1E1这种就没分数了，sonarr会提示Not a Custom Format upgrade for existing episode file(s)

**Comment by WoodC2011** [comment]
另外还有个BUG，

我下动漫的时候遇到过几次，就是下载文件如果有三四层文件夹，最终的.mkv文件不会被重命名，也无法自动导入，只能手动

**Comment by LuckyPuppy514** [comment]
> 另外还有个BUG，
> 
> 我下动漫的时候遇到过几次，就是下载文件如果有三四层文件夹，最终的.mkv文件不会被重命名，也无法自动导入，只能手动

跟文件夹层数没关系，.mkv 没有重命名，更有可能是因为文件名有问题，无法根据现有规则提取到季数和集数，无法重命名

**Comment by WoodC2011** [comment]
> > 我不太明白你说的
> > 但我刚才试了下test版本，文件夹里的mkv文件命名现在正确了，也可以正常升级了
> 
> 我的意思是，我股市改了，分数还是一样

我找到原因了，S1E1这种格式，如果给了负分，导入的时候会反映出来（原来比如2600分，导入的时候只会显示-10000），比如像我给了不含中文标识的标题负分，所以导致显示-10000分

我在他们的discord群里问了下，sonarr那边不太支持S1E1这种命名方式，即便现在暂时能显示历史分数，最好还是用原标题，原标题jproxy不都是格式化过的，应该不会有大问题吧？

**Comment by LuckyPuppy514** [comment]
主要是追加了其他信息分数还是不对，而且还有可能影响季数和集数的识别
现在你用着有什么问题么，没什么问题我就上正式环境了，我这边升级的情况还是比较少的，暂时没发现什么问题

**Comment by WoodC2011** [comment]
我之前出问题主要是因为S1E1这种因为没任何中文标识被我设置了负分，不设置负分的话就没什么影响不会影响升级。我加了正则屏蔽掉S1E1这种的得分就没事了。主要是看是否有人给s1e1负分。

sonarr官方是认为都得加上的，但确实不加也有得分，不知道算不算bug，但一旦s1e1这种没得分的话肯定就无法升级了

test版我测试了几集没发现有什么问题，我不太清楚你之前只用s1e1的用意，是怕顾客乱改自定义格式出错吗？按理来说只要文件标题和网页标题一致并不会影响导入吧。

**Comment by LuckyPuppy514** [comment]
sonarr 导入的时候，识别跟种子名称，文件名称都有关系，一般其他信息通过种子名称就能识别到，文件名称只需要季数和集数即可，即使追加了其他信息，至少在分数方面来看，也不会产生积极影响，反而有可能对其他信息识别产生干扰（具体的情况忘记了，以前出现过，所以只保留了季数和集数）

**Comment by WoodC2011** [comment]
我这边的话，test版本显示的得分和搜索的时候显示的得分是一致的，如果你那不对，会不会也是和负分有关系

**Comment by WoodC2011** [comment]
如果加了有影响的话，我感觉还是不升级好一点

**Comment by LuckyPuppy514** [comment]
我没有负分，少了 1000 分是 `1080P` 的分数，但是明显文件名有

**Comment by WoodC2011** [comment]
可能是个bug？我用test版之前偶尔也会遇到一些显示负六七千的（一万负分加上2000多正分），也有只显示负一万分的。

但test版我也没长时间用，我前天只对比了一部动漫的一集，显示是正常的导入也没问题（即便我没屏蔽s1e1的-10000分）

**Comment by WoodC2011** [comment]
> 我没有负分，但是少了 1000 分是`1080P`分数，明显文件名有

我测试了两天，我追了70来个番，test版升级每出错过，以前错误很多，主要test版分数都是对的，导入的时候不会有冲突

而且即便加上自定义格式出错，这个也是sonarr的故障，大佬能升级下版本到3.4.1吗

**Comment by LuckyPuppy514** [comment]
已发，等几分钟就可以拉镜像了

**Comment by WoodC2011** [comment]
https://github.com/Sonarr/Sonarr/issues/5295

如果你像我一样设置了季包优先，或者给了S1E1这种某个分数，会导致季包里的文件的得分跟搜索结果不一样，不知道你那个1080是不是类似的原因。

但由于Jproxy把集包的命名设置成了S1E1开头的形式，只要单独写个正则以匹配S1E1开头的剧集文件，然后额外配置文件里给S1E1和S1一样的分数，最终得分应该就一致了

**Comment by WoodC2011** [comment]
> 我没有负分，少了 1000 分是 `1080P` 的分数，但是明显文件名有

你有设置S1、S1E1这种类型的正则的分数吗，无论正负分

**Comment by LuckyPuppy514** [comment]
> > 我没有负分，少了 1000 分是 `1080P` 的分数，但是明显文件名有
> 
> 你有设置S1、S1E1这种类型的正则的分数吗，无论正负分

没有，我的分数规则很简单的，就几个

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/d0ffdd3e-3c32-451d-95a8-3c1a146aeed0)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/b582c7d6-f174-454e-b8df-f87d2a8b7661)

**Comment by WoodC2011** [comment]
3.4,1之后，历史记录里分还不对吗，我这比较了五六个，分数都完全正确了，而且历史记录里之前分不对的现在也对了

**Comment by LuckyPuppy514** [comment]
> 3.4,1之后，历史记录里分还不对吗，我这比较了五六个，分数都完全正确了，而且历史记录里3.4.0的时候分不对的现在也对了

我用的 v4 开发版 😂

**Comment by WoodC2011** [comment]
我也是sonarr V4，我意思是jproxy 3.4.1
