### ISSUE TITLE
sonarr的qb配置没有Url base参数设置项

### ISSUE THREAD

**Issue by SiIentZephyrus** [LuckyPuppy514/jproxy#8]
**描述错误情况 - Describe the bug**
请尽可能清楚的描述你遇到的问题
3.0.9.1549的sonarr版本添加Download Clients的qb时，没有Url base参数，jproxy中qBittorrent的代理路径也无法修改，怎么办？

**截图 - Screenshots**
请提供错误全屏截图

**请提供以下信息 - Desktop (please complete the following information):**
 - OS: [e.g. docker/linux/windows]
 - Version [e.g. 2.5.1]

**日志 - log**
请提供详细的错误日志
Please provide web_error.log.

**Comment by LuckyPuppy514** [comment]
打开 Sonarr 高级设置就有了
![image](https://user-images.githubusercontent.com/53246532/183358047-0e448034-fa95-47eb-afae-4a1fcf179baa.png)

**Comment by SiIentZephyrus** [comment]
> 打开 Sonarr 高级设置就有了 ![image](https://user-images.githubusercontent.com/53246532/183358047-0e448034-fa95-47eb-afae-4a1fcf179baa.png)

好的，设置好了，感觉用了确实多了很多资源可以选择

**Comment by LuckyPuppy514** [comment]
动漫我已经写了20多个字幕组规则，大部分应该都可以了
有问题欢迎反馈，想要写规则可以看wiki，或者提个规则需求上来
