### ISSUE TITLE
jproxy改名过的下载文件无法转移到transsmission

### ISSUE THREAD

**Issue by WoodC2011** [LuckyPuppy514/jproxy#80]
**部署环境（windows / docker）**

docker

**问题描述**

jproxy把下载文件改名，然后导入到sonarr以后。我用iyuu把种子从qbittorrent转移到trasnsmission，转移过来的种子都会校验失败（下载文件名不一样了，种子还是同一个）。

**Comment by LuckyPuppy514** [comment]
按照你的描述，重命名就有问题的话，那就没办法，你只能自己均衡选择了，重命名是可以关闭的

1. 关闭文件重命名，可以在 REDAME.md docker 参数中找到对于的配置；
2. 关闭种子重命名和文件重命名，可以在页面中移除下载器的配置即可；

**Comment by WoodC2011** [comment]
不好解决的话我就不转移了，还是自动改名比较重要些
