### ISSUE TITLE
创建路径循环导致sonarr导入失败

### ISSUE THREAD

**Issue by Ink-Sakura** [LuckyPuppy514/jproxy#81]
**部署环境（windows / docker）**

windows11

**问题描述**

在sonarr里订阅下载番剧时，有时会出现下载目录里同一番剧多个集在一个文件夹里，各集的路径之后出现循环创建的情况。
第一次提问之后发现只要是bt软件里种子名能变过来就ok了，没变就寄了。
感觉是不是跟我操作太频繁有关系...因为那时一直下不好就一直重新操作...隔一段时间就好了...|||

**相关日志**

[jproxy.log](https://github.com/LuckyPuppy514/jproxy/files/13205412/jproxy.log)
[jproxy-error.log](https://github.com/LuckyPuppy514/jproxy/files/13205414/jproxy-error.log)

**相关截图**

![屏幕截图 2023-10-30 001454](https://github.com/LuckyPuppy514/jproxy/assets/114347625/11e1b4cb-5a88-40b9-b57b-04a8f38ecd46)

**Comment by LuckyPuppy514** [comment]
那你先观察一段时间，不要频繁手动重下同一个种子，多集在同一个目录也没有问题，因为重命名后，同一部剧父文件夹的确可能同名

**Comment by Ink-Sakura** [comment]
（主要是不停的循环创建目录导致sonarr导入不了）好的吧...
刚才还发现...sonarr有时同一集会抓多次，这我就不太能确定问题在哪啦...以前只用sonarr时应该是没出现过这个情况...
![屏幕截图 2023-10-30 215903](https://github.com/LuckyPuppy514/jproxy/assets/114347625/2a6b1c75-8d8a-483f-927f-0806529c2900)

**Comment by LuckyPuppy514** [comment]
请不要这样发截图，你应该截图整个界面，把抓取记录所有信息都展示出来，否则只有一个标题，根本判断不出什么原因

**Comment by LuckyPuppy514** [comment]
应该把两条重复抓取的记录，像我这样截图

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/598ff235-fee8-4995-8482-9333b56980a3)

**Comment by Ink-Sakura** [comment]
说的也是，傻了...
确实是release profile那儿的机制问题，我没研究...直接凭直觉操作的...
非常感谢您owo！
