### ISSUE TITLE
pthome.net的副标题获取不到

### ISSUE THREAD

**Issue by PN62323424** [LuckyPuppy514/jproxy#83]
**部署环境（windows / docker）**

docker
默认剧集规则（仅添加了第01-14集相关的规则）

**相关截图**

以这个链接为例，副标题里的所有内容都获取不到，导致无法下载集
https://www.pthome.net/details.php?id=173793&hit=1

主标题：[无所畏惧] The Fearless 2023 S01 2160p WEB-DL HEVC DDP5.1 2Audios-QHstudIo
副标题：无所畏惧 第01-14集【杜比环绕】【主演: 热依扎 | 王阳 | 啜妮 | 沈羽洁 | 李煜】QHstudIo小组作品

**Comment by LuckyPuppy514** [comment]
这个问题你得先看 Jackett / Prowlarr 接口返回的数据是否有副标题的数据，如果没有 JProxy 也无能为力
我没有这个站所有无法测试，以 Prowlarr 为例，测试方法如下：

1. 访问如下地址

```txt
http://IP:端口号/你这个站点的ID/api?q=The%20Fearless&t=tvsearch&ep=1&apikey=填写你的APIKEY
```
例如：`http://192.168.6.5:9696/11/api?q=The%20Fearless&t=tvsearch&ep=1&apikey=cfc******45b`

2. 在接口返回的数据中寻找是否有副标题，一般在  `<description>` 标签中

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/4e9af655-e33b-4a8e-9dd3-ec35a98ae3cb)

**Comment by PN62323424** [comment]
我用的是jackett，jackett的话，站点ID指的是jackett里的什么

http://192.168.6.5:9117/站点ID/api?q=The%20Fearless&t=tvsearch&ep=1&apikey=cfc******45b

**Comment by LuckyPuppy514** [comment]
Jackett 链接不一样，直接复制你索引器配置里面的地址 + /api 就行，? 后面的参数一样

**Comment by PN62323424** [comment]
http://192.168.6.5:9117/api/v2.0/indexers/pthome/results/torznab/api?q=The%20Fearless&t=tvsearch&ep=1&apikey=xxxxxxxxxxxxxxxxx

返回的数据是这样，是不是不行了：

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="100" description="Invalid API Key">
<SCRIPT id="allow-copy_script">(function agent() { let unlock = false document.addEventListener('allow_copy', (event) => { unlock = event.detail.unlock }) const copyEvents = [ 'copy', 'cut', 'contextmenu', 'selectstart', 'mousedown', 'mouseup', 'mousemove', 'keydown', 'keypress', 'keyup', ] const rejectOtherHandlers = (e) => { if (unlock) { e.stopPropagation() if (e.stopImmediatePropagation) e.stopImmediatePropagation() } } copyEvents.forEach((evt) => { document.documentElement.addEventListener(evt, rejectOtherHandlers, { capture: true, }) }) })()</SCRIPT>
</error>
```

**Comment by LuckyPuppy514** [comment]
这不是写着 `Invalid API Key` 无效的 apikey 吗，自行检查你的密钥

**Comment by PN62323424** [comment]
```
      <title>The Fearless Hyena 1979 WEB-DL 1080p H264 AAC-PTHome</title>
      <guid>https://www.pthome.net/download.php?id=47789&amp;hit=1</guid>
      <jackettindexer id="pthome">PThome</jackettindexer>
      <type>private</type>
      <comments>https://www.pthome.net/details.php?id=47789&amp;hit=1</comments>
      <pubDate>Mon, 30 Sep 2019 22:57:08 +0800</pubDate>
      <size>1964947584</size>
      <grabs>33</grabs>
      <description />
```

description里没内容

**Comment by LuckyPuppy514** [comment]
那就没办法
