### ISSUE TITLE
在文件下载完并成功导入之后，改回原来的名字保证做种

### ISSUE THREAD

**Issue by Left024** [LuckyPuppy514/jproxy#84]
**问题描述**

Hi，今天发现这个项目用了感觉非常棒！感谢开发者
但在使用时有一个小问题，如标题所说，在下载完之后因为 BT 客户端的文件名被改了，所以导致不能继续做种

**功能描述**

在检测到下载导入任务完成后修改回种子原始文件名，使得种子可以继续做种

**Comment by LuckyPuppy514** [comment]
一般改名不影响做种，你是不是用了什么辅种工具，比如 IYUU，这种我个人没用，暂时也不打算支持
如果需要刷流，可以找几个大包挂着，或者搞个盒子，刷一次一般人能用很久吧 🤣

**Comment by Left024** [comment]
您的这个工具我主要是用来解决追番的问题，刚刚试用 mikan 下了一集，改完名就完全没有做种了
虽然 mikan 不是 PT 站也没有做种要求，但是我个人认为做做种维护 BT 环境还是很有必要的

**Comment by LuckyPuppy514** [comment]
这个应该是你客户端做种设置的问题，种子重命名都是用的下载客户端的接口，我个人做种是没问题的

**Comment by Left024** [comment]
好的，感谢回复，我再用用看看吧

**Comment by LuckyPuppy514** [comment]
最简单的你可以自己手动下载一个试试，看看下载完会不会做种，就知道是不是你的设置的问题了
