### ISSUE TITLE
TMDB URL 无效

### ISSUE THREAD

**Issue by kristianvmd** [LuckyPuppy514/jproxy#85]
**部署环境（windows / docker）**

docker

我是用的http代理，不知道是不是这个原因，提示是TMDB URL 无效
docker run --name jproxy \
--restart=always \
-e PUID=0 \
-e PGID=0 \
-e TZ=Asia/Shanghai \
-e JAVA_OPTS="-Xms512m -Xmx512m" \
-e HTTP_PROXY=http://192.168.31.100:7890 \
-e HTTPS_PROXY=http://192.168.31.100:7890 \
-p 8117:8117 \
-v /volume1/docker/jproxy/database:/app/database \
-d luckypuppy514/jproxy:latest

简要描述复现问题的操作，以及出现的具体问题

**相关日志**

docker 请执行 `docker logs -f jproxy` 并重新执行复现问题的操作截取重新操作后的日志
windows 在 logs 目录下

```
 ERROR [xec-2] com.lckp.jproxy.util.CheckUtil.checkTmdbApi(CheckUtil.java:156)                  : TMDB URL 无效：I/O error on GET request for "https://api.themoviedb.org/3/movie
```

**Comment by kristianvmd** [comment]
抱歉

**Comment by kristianvmd** [comment]
我是容器装的http代理，似乎也不行，但其它容器可以的，只不过用的是docker官方的http代理变量

docker run --name jproxy \
--restart=always \
--link openclash:openclash \
--privileged \
-e PUID=0 \
-e PGID=0 \
-e TZ=Asia/Shanghai \
-e JAVA_OPTS="-Xms512m -Xmx512m -Dhttp.proxyHost=172.17.0.1 -Dhttp.proxyPort=7890" \
-p 18117:8117 \
-v /volume1/docker/jproxy/database:/app/database \
-d luckypuppy514/jproxy:latest

错误日志
```
22:06:24.091 ERROR [ec-10] com.lckp.jproxy.util.CheckUtil.checkTmdbApi(CheckUtil.java:156)                  : TMDB URL 无效：I/O error on GET request for "https://api.themoviedb.org/3/movie/550": Connect timed out
22:09:16.235 ERROR [xec-5] com.lckp.jproxy.util.CheckUtil.checkTmdbApi(CheckUtil.java:156)                  : TMDB URL 无效：I/O error on GET request for "https://api.themoviedb.org/3/movie/550": Connect timed out
```

**Comment by kristianvmd** [comment]
我返回的就是你发的：
```
root@icloud:~# docker exec -it jproxy curl -x "http://172.17.0.1:7890" "https://api.themoviedb.org"
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by LuckyPuppy514** [comment]
那就进 JProxy 容器内部，执行

```bash
echo $JAVA_OPTS
```

```bash
curl -x "http://172.17.0.3:7890" "https://api.themoviedb.org"
```

然后截图发出来看看

**Comment by kristianvmd** [comment]
```
root@icloud:~# docker exec -it jproxy sh
# echo $JAVA_OPTS
-Xms512m -Xmx512m -Dhttp.proxyHost=172.17.0.1 -Dhttp.proxyPort=7890
# curl -x "http://172.17.0.3:7890" "https://api.themoviedb.org"
curl: (7) Failed to connect to 172.17.0.3 port 7890 after 0 ms: Connection refused
# curl -x "http://172.17.0.1:7890" "https://api.themoviedb.org"
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by LuckyPuppy514** [comment]
怎么一会 172.17.0.3，一会 172.17.0.1，你自己先确定好自己的代理，现在看起来没有问题，你确定保存还是提示连接超时？

**Comment by kristianvmd** [comment]
> 怎么一会 172.17.0.3，一会 172.17.0.1，你自己先确定好自己的代理，现在看起来没有问题，你确定保存还是提示连接超时？

我只是删过一次IP变了，所以改了下， 我确定保存还是提示连接超时，试了好多次了

**Comment by kristianvmd** [comment]
昨天就试过重新创建，而且我还换了个设备试了下，也是不行的。

**Comment by LuckyPuppy514** [comment]
删除镜像，重拉后重新创建，还有可以试试 socks 代理，怎么设置请看 README

**Comment by kristianvmd** [comment]
删除镜像重新创建和socks代理也试了，也都不行，socks代理下执行```docker exec -it jproxy curl -x "http://172.17.0.1:17890" ```也是正常的

```
root@icloud:~# docker exec -it jproxy curl -x "http://172.17.0.1:17890" "https
://api.themoviedb.org"
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by LuckyPuppy514** [comment]
socks 代理你怎么还用 http 协议，应该是 

```bash
docker exec -it jproxy curl -x "socks://172.17.0.1:17891" "https://api.themoviedb.org"
```

**Comment by LuckyPuppy514** [comment]
这个应该没啥问题，你尝试按 README 文档使用 socks 代理创建容器了吗
如果还不行，只能加Q群：921905633 找我，我远程看看了

**Comment by NNuuNN** [comment]
wtf。。。搞了一晚上。。。把地址换成api.tmdb.org搞定了。。。

**Comment by kristianvmd** [comment]
> wtf。。。搞了一晚上。。。把地址换成api.tmdb.org搞定了。。。

本来不就是api.tmdb.org吗，你最后是怎么搞定的

**Comment by NNuuNN** [comment]
> > wtf。。。搞了一晚上。。。把地址换成api.tmdb.org搞定了。。。
> 
> 求教，你最后是怎么搞定的

你上面的流程我都跑了一遍，没问题，但是用默认的https://api.themoviedb.org就是红叉
在系统设置-基础设置-TMDB  那把服务地址改为api.tmdb.org  保存就绿勾了

**Comment by kristianvmd** [comment]
> > > wtf。。。搞了一晚上。。。把地址换成api.tmdb.org搞定了。。。
> > 
> > 
> > 求教，你最后是怎么搞定的
> 
> 你上面的流程我都跑了一遍，没问题，但是用默认的[https://api.themoviedb.org就是红叉](https://api.themoviedb.org%E5%B0%B1%E6%98%AF%E7%BA%A2%E5%8F%89) 在系统设置-基础设置-TMDB 那把服务地址改为api.tmdb.org 保存就绿勾了

这里是绿勾了，但qbittorrent那里变红勾了，你qbit那里没问题的？

**Comment by NNuuNN** [comment]
> > > > wtf。。。搞了一晚上。。。把地址换成api.tmdb.org搞定了。。。
> > > 
> > > 
> > > 求教，你最后是怎么搞定的
> > 
> > 
> > 你上面的流程我都跑了一遍，没问题，但是用默认的[https://api.themoviedb.org就是红叉](https://api.themoviedb.org%E5%B0%B1%E6%98%AF%E7%BA%A2%E5%8F%89) 在系统设置-基础设置-TMDB 那把服务地址改为api.tmdb.org 保存就绿勾了
> 
> 这里是绿勾了，但qbittorrent那里变红勾了，你qbit那里没问题的？

嗯，这个就需要你测试下了，比如代理，qb，jproxy是否在一个网络中，我测试了很久，最终是clash在bridge，qb jp在host下，地址你要测试下，局域网地址，127，或者172反正都试试

我在想我们俩遇到的这些问题，就themoviedb红叉，tmdb绿勾的情况，是否跟我们用的代理服务支不支持udp有关。

**Comment by yztz** [comment]
把 `-Dhttp.proxyHost=XXX -Dhttp.proxyPort=XXX` 改成 `-Dhttps.proxyHost=XXX -Dhttps.proxyPort=XXX `
