### ISSUE TITLE
导入时语言识别不对导致无法导入

### ISSUE THREAD

**Issue by Left024** [LuckyPuppy514/jproxy#86]
**原始标题**

```text
[豌豆字幕组&风之圣殿&LoliHouse] 咒术回战 / Jujutsu Kaisen - 44 [WebRip 1080p HEVC-10bit AAC][简繁外挂字幕]
```

**问题描述**

在 RSS 刷新时，可以正确根据标题抓取下载，但是在下载完之后，视频文件的语言会被识别为其他语言而导入失败（为了保证下载正确我设置了其它语言扣分）
![image](https://github.com/LuckyPuppy514/jproxy/assets/20574903/54d2db3d-7f91-46e9-8964-f82b5468b07d)

我想尝试在匹配到的语言前面增加 ```Chinese``` 字段来让 Sonarr 识别正确，实测下来标题确实按照我所预想的变更了，但是文件夹内容依然没有改变
![image](https://github.com/LuckyPuppy514/jproxy/assets/20574903/8540abc9-35b4-493d-b959-1088a203402b)
![image](https://github.com/LuckyPuppy514/jproxy/assets/20574903/017db5d6-3261-4ffb-b876-fcc194b7280a)

想请教下是我哪里做的不对吗？

**Comment by LuckyPuppy514** [comment]
不要用这种格式：`Chinese - [简繁]`，应该用：`[Chinese][简繁]`
不过即使你改了应该也没有意义，因为这好像是 Sonarr 的 BUG

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/c5d4ad8e-bfca-4fac-9123-77061d2777b1)

中文我这边有个 +1000 分的自定义格式，每次抓取没问题，但是导入的时候分数就不对，不过我这边不影响导入，Sonarr 版本是 v4

**Comment by Left024** [comment]
我也是 v4
我读了文档，文档的意思是下载完之后会根据种子内的文件名重新计算分数，所以分数不对
我也给中文设置了加分的自定义格式，但是有时候生肉的质量通常比字幕组高，为了避免下载到生肉，我同时设置了除中文外-10000分
所以就出现了图上的情况，爬取时根据标题分数正常，下载完根据种子文件重新计算，然后变成负分，导入失败

就是不知道为什么 Qb 里面的种子文件明明也有“简体”这些字段，但就是会识别成日语或其它语言

**Comment by LuckyPuppy514** [comment]
可以参考我的设置，把中文分数拉高，不要用负分，我这边一直都正常，没有下载过生肉

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/97d4dc0a-e1a1-4549-bc45-0877540f8036)

**Comment by Left024** [comment]
理解您的意思了，还有另一个问题想请教下

按照您的逻辑设置后下载，下载完之后的文件再次计算时 ```Chinese``` 的分数因为识别不到就不会加上去

后续 Rss 扫描时扫到相同文件因为标题的 ```Chinese``` 分数比已下载的文件高，就会添加重复下载，这个问题如何解决呢？

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/474a92bd-25ad-4006-8923-17ba9a7e81fa)

不要开升级，有需要自己多设置几个质量配置，需要升级自己切换质量配置

**Comment by Left024** [comment]
好的明白了，感谢回复
