### ISSUE TITLE
自己写的规则，测试范例正常，实际标题没有按照规则修改

### ISSUE THREAD

**Issue by Left024** [LuckyPuppy514/jproxy#89]
**原始标题**

```text
[ANi] 我内心的糟糕念头 第二季 - 14 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4]
```

原始种子页面：https://mikanani.me/Home/Episode/59dbd9437070b9600f6eaadb64c878a8e583e515

**问题描述**
我写的正则表达式（小白，对着ChatGPT改的），在测试范例中工作正常，但是 rss 中没有变化。
```
.*(我内心的糟糕念头|我內心的糟糕念頭|我心里危险的东西|Boku no Kokoro no Yabai Yatsu|The Dangers in My Heart).*(| )(|第)(1[3-9]|2[0-5])(|集|话|話)(| ).*
```
![image](https://github.com/LuckyPuppy514/jproxy/assets/20574903/491e2b7f-c99a-4fde-adef-c337b77b0e09)
![image](https://github.com/LuckyPuppy514/jproxy/assets/20574903/bae7700d-1de0-44a6-bbbb-7259094de2d1)

**Comment by LuckyPuppy514** [comment]
优先级给得太大了，你得加到剧集范例里面看是否生效，测试前最好清除一下所有缓存

**Comment by Left024** [comment]
> 优先级给得太大了，你得加到剧集范例里面看是否生效，测试前最好清除一下所有缓存

改成1000就好了
