### ISSUE TITLE
全部配置为https，sonarr无法添加indexer，全设置为http就正常

### ISSUE THREAD

**Issue by dalamudx** [LuckyPuppy514/jproxy#9]
**描述错误情况 - Describe the bug**
**描述你的需求 - Describe Requirement**
不知现在这个项目是否支持https，环境里jackett、sonarr、qb都是支持https的，jproxy也用nginx反代了，但是测试了下，失败了
同样的配置，全走http就正常

**截图 - Screenshots**
![image](https://user-images.githubusercontent.com/88395653/193422509-b1856b29-0125-4051-960b-67dfef0901c1.png)

**请提供以下信息 - Desktop (please complete the following information):**
 - OS: docker
 - Version: 2.6.4

**日志 - log**
以下是sonarr添加https的indexer时报错日志
```
[Warn] SonarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details 
[Warn] HttpClient: HTTP Error - Res: [GET] https://nas.xxxx.com:8117/jackett/api/v2.0/indexers/bangumi-moe/results/torznab/api?t=caps&apikey=emh8ao0qxup1834imw5ou7tm3dc3hrhz: 403.Forbidden (11939 bytes) 
[Warn] Torznab: Unable to connect to indexer 

[v3.0.9.1549] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://nas.xxxx.com:8117/jackett/api/v2.0/indexers/bangumi-moe/results/torznab/api?t=caps&apikey=emh8ao0qxup1834imw5ou7tm3dc3hrhz]
```
以下是jproxy日志
```
2022-10-02 02:03:00.776  INFO 7 --- [nio-8117-exec-8] c.lckp.controller.ProxyConfigController  : 代理配置 - 测试：{"proxyIp":"nas.xxxx.com","proxyPath":"/jackett/**","proxyPort":"9117","proxyType":"Jackett"}
2022-10-02 02:03:02.012  INFO 7 --- [nio-8117-exec-4] c.lckp.controller.ProxyConfigController  : 代理配置 - 修改：{"proxyIp":"nas.xxxx.com","proxyPath":"/jackett/**","proxyPort":"9117","proxyType":"Jackett"}

```

**Comment by LuckyPuppy514** [comment]
**强烈建议不要暴露到外网**
- 因为 sonarr, jproxy, jackett 所有请求都是在服务端进行的，填对应的内网地址就能互相访问了（同一个内网，即使你浏览器不能访问也没问题）

> https 应该也是没问题的，看你日志是 403 ，一般是没登陆，你是否做了第三方认证

**Comment by LuckyPuppy514** [comment]
都建议用内网 IP + 端口，这些系统请求都是在服务端进行的，既安全又更快
![image](https://user-images.githubusercontent.com/53246532/193423760-d36df351-a926-4d2f-a98c-ae08eebc8034.png)

**Comment by dalamudx** [comment]
> **强烈建议不要暴露到外网**
> 
> * 因为 sonarr, jproxy, jackett 所有请求都是在服务端进行的，填对应的内网地址就能互相访问了（同一个内网，即使你浏览器不能访问也没问题）
> 
> > https 应该也是没问题的，看你日志是 403 ，一般是没登陆，你是否做了第三方认证

找到问题原因了，jproxy的nginx配置有问题改了之后可以了，但是jproxy连jackett默认是走http，先这样吧。
