### ISSUE TITLE
能否增加英文标题（不含S01)搜索

### ISSUE THREAD

**Issue by kristianvmd** [LuckyPuppy514/jproxy#91]
示例标题：
```
Digimon Frontier 2002 1080P BDRip FLAC x264-LowPower-Raws
```

jackett搜索日志
```
01-20 14:24:19 Info Torznab search in M-Team - TP for Digimon Frontier S01 => Found 0 releases (from cache) [0ms]
01-20 14:24:19 Info Torznab search in M-Team - TP for 数码宝贝04无限地带 S01 => Found 0 releases (from cache) [0ms]
01-20 14:24:19 Info Torznab search in M-Team - TP for 數碼寶貝04無限地帶 S01 => Found 0 releases (from cache) [0ms]
01-20 14:24:19 Info Torznab search in M-Team - TP for 数码宝贝04无限地带 => Found 0 releases (from cache) [0ms]
```

像这部动漫，中文名很复杂我看了下发布的基本都是错的，英文名很多又不带S01，就会导致搜不出来，如果除了搜中文名之外加个英文名搜索就可以了

而且遇到这种情况的话，当前即便用jproxy，应该也是无能为力的，因为改不了搜索词，允许更改搜索词您有没考虑过

**Comment by LuckyPuppy514** [comment]
这种应该是个别情况，当前可以参考下面的设置

1. 在 TMDB 中搜索对应的剧集，删除已有标题

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/a72ef397-d34b-4e20-828d-0d2dd8c520c7)

2. 新增需要搜索的英文标题

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/d6ca71af-2134-4959-a133-654d2e789c95)

当然，你也可以直接修改第一个中文标题（会去除季集搜索的标题是 TMDB 对应剧集搜索到的第一个标题，按添加时间顺序排序）

**Comment by kristianvmd** [comment]
学到了，感谢
