### ISSUE TITLE
标题里含jade和viutv的情况

### ISSUE THREAD

**Issue by kristianvmd** [LuckyPuppy514/jproxy#92]
jade和viutv是港剧的标题的开头（电视台名字），像jade在馒头搜的话有四千多个都是这样的量非常大了，标题如果用jade和viutv开头的都识别不出来，这个能jproxy那一侧解决下吗？

**Comment by LuckyPuppy514** [comment]
给几个例子看看什么情况

**Comment by kristianvmd** [comment]
你在馒头综合里搜jade，四五千个结果，都是开头是jade的，开头是viutv也有几百

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/84619573-dffc-4a5d-8c40-73afbcc12957)

那你可以修改以下设置，这样净标题会去除相应的内容，标题匹配的时候就不会被干扰

```text
(`|,|~|!|@|#|%|&|_|=|'|"|:|<|>|-|—|·|，|～|、|。|‘|’|“|”|？|！|：|（|）|【|】|《|》|♀)
```

替换为

```text
(`|,|~|!|@|#|%|&|_|=|'|"|:|<|>|-|—|·|，|～|、|。|‘|’|“|”|？|！|：|（|）|【|】|《|》|♀|(?i)Jade|viutv)
```

`|` 代表：或，`(?i)` 代表：忽略大小写

如果你确定这两个内容一定在标题开头，可以添加 ^ 更为准确，避免影响有些剧集标题真的含有这两个词

```text
(`|,|~|!|@|#|%|&|_|=|'|"|:|<|>|-|—|·|，|～|、|。|‘|’|“|”|？|！|：|（|）|【|】|《|》|♀|^(?i)Jade|^viutv)
```

最后记得清除一下所有缓存

**Comment by kristianvmd** [comment]
感谢大佬，我一直以为这个地方只是用来去掉tvdb或者tmdb里的原始标题特殊符号的，原来是去除发布标题的
