### ISSUE TITLE
识别的一些常见错误

### ISSUE THREAD

**Issue by kristianvmd** [LuckyPuppy514/jproxy#95]
**问题描述**

以下这些标题基本都无法识别，而且占据了剧集及电影不能识别的大部分情况：
Yu Yu Hakusho new 2023 S01——无法识别因为后面有个new——标题后面额外的单词干扰
Yu Yu Hakusho complete 2023 S01——无法识别因为后面有个complete——标题后面额外的单词干扰
Yu Yu Hakusho 2023 S01——会被识别为1992版的实际是2023版的——重名导致的干扰
CCTV Yu Yu Hakusho  S01 1992——无法识别因为前面有CCTV——标题前面额外的单词干扰
the Yu Yu Hakusho  S01 1992——会和不含the的剧集产生识别问题

**功能描述**
能否让jproxy在剧集或者电影识别的时候自动加上年份识别，即识别的时候剧集名和年份比对是否一致作为第一优先级来判断是哪部剧集，同时包含则Yu Yu Hakusho和1992则认为是Yu Yu Hakusho，同时包含则Yu Yu Hakusho和2023则认为是Yu Yu Hakusho (2023)

TVDB里重名剧集后面都要求带年份的，Yu Yu Hakusho和Yu Yu Hakusho (2023)是两部不同的剧集

这样以上三种非常常见的情况，就都可以准确识别了

**Comment by LuckyPuppy514** [comment]
1. `new`、`complete`、 `CCTV` 可以参考 #92 
2.  `the` 的问题请参考 #94 
3. 年份的问题，Sonarr 暂时没有使用年份进行判断，Radarr 已经有进行年份匹配了（前提是发布标题中包含了年份，不包含还是只根据净标题进行匹配）
