### ISSUE TITLE
手动搜索时别称失效

### ISSUE THREAD

**Issue by GRCXII** [LuckyPuppy514/jproxy#96]
**部署环境（windows / docker）**

windows

**问题描述**

进行手动搜索时sonarr通过jproxy发送的别称搜索带有剧集参数导致别称搜索基本失效

**相关截图**

<img width="1908" alt="image" src="https://github.com/LuckyPuppy514/jproxy/assets/99615877/55d62185-7381-47f3-8e2d-12a63182fb76">

带剧集参数的搜索结果全部为零

**相关日志**

sonarr

2024-02-02 10:00:40.8|Info|ReleaseSearchService|Searching indexers for [Gushing Over Magical Girls : S01]. 1 active indexers
2024-02-02 10:00:52.3|Info|DownloadDecisionMaker|Processing 61 releases
2024-02-02 10:01:36.7|Info|ReleaseSearchService|Searching indexers for [Gushing Over Magical Girls : S01E05]. 1 active indexers
2024-02-02 10:01:40.7|Info|DownloadDecisionMaker|Processing 61 releases

<img width="813" alt="image" src="https://github.com/LuckyPuppy514/jproxy/assets/99615877/90bb7da7-1c5f-4f38-9963-48ae9987df9f">

所有抓取结果都是用追加的不带参数搜索的主称搜索到的

使用jackett搜索结果一样

jproxy能增加过滤掉`&season=xx&ep=xx`参数的开关吗

**Comment by LuckyPuppy514** [comment]
这样太简单粗暴了，而且现在有逻辑会在查到结果比较少的时候，自动去除 season 和 ep 进行搜索的

**Comment by GRCXII** [comment]
> 这种个别的情况，我建议你直接在 sonarr 手动搜，不行就在 Prowlarr / Jackett 手动搜，下载整季的包，然后手动导入

sonarr还有更手动的搜吗，我这个issue就是用的那个互动搜索啊

**Comment by GRCXII** [comment]
> > 这样太简单粗暴了，而且现在有逻辑会在查到结果比较少的时候，自动去除 season 和 ep 进行搜索的
> 
> 我知道现在有那个追加主名搜索的逻辑，但是只追加主名搜索对于mikan这种源站好像也不够全面？mikan这种站带剧集参数好像啥都搜不到

能不能在搜索结果为零时追加主名与别名的不加剧集参数的搜索？

**Comment by GRCXII** [comment]
> 这种都是少数情况，中文标题不加季集都搜不到，基本上很少能搜到结果，有需要改成其他语言标题搜索，建议看这个 #91 

可是我这边使用mikan时只要带剧集参数的都搜索不到结果，结果全都是追加的无剧集参数主名搜索搜到的。

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/82766e92-e1c3-40b7-abde-4b28a97e8b7b)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/f0dca98c-0f34-4e85-bd12-d039957c5451)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/24dfbd1e-50be-4f74-95fb-f2fb7823fcd7)

我这里一搜很多结果，明显是你的 Sonarr 设置的问题

我看你的截图，出现了 Season 1 和 Episode 5 的参数，这种明显是你
1. 把 Series Type 设置成了 Standard
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/986a250d-30b9-4daa-b864-5bd43e9b7698)
2. 或者索引器设置以动漫标准格式搜索，或者你选择错了分类和动画分类
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/2bbfebb0-2711-418b-b88f-ea6d88d24c47)

针对1，可以使用 Jellyseerr（Emby） 或 Overseerr (Plex) 这种搜索应用解决
针对2，强烈建议不要勾选以动漫标准格式搜索，除非你知道你在干嘛，并且在动画分类勾选，Series Type 为 Anime 对于的分类
